/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server;

import java.util.HashMap;
import java.util.Map;

import ir.notifaano.server.models.*;

public class Configuration {
    /**
     * Current API environment
     */
    public static Environments environment = Environments.INSURANCE_SERVER_NOTIFAANO_IR;

    /**
     * Get base URI by current environment
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public static String getBaseUri(Servers server) {
        StringBuilder baseUrl = new StringBuilder(environmentMapper(Configuration.environment, server));
        Map<String, Object> parameters = new HashMap<String, Object>();
        APIHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }
    
    /**
     * Get base URI by current environment
     * @return Processed base URI
     */
    public static String getBaseUri() {
        return Configuration.getBaseUri(Servers.SERVER_1);
    }
    
    /**
     * Base URLs by environments and server aliases 
     */

    private static String environmentMapper(Environments environments, Servers servers) {
		String url = "";
		if(environments.equals(Environments.INSURANCE_SERVER_NOTIFAANO_IR)) {
			if(servers.equals(Servers.SERVER_1))
				url = "http://server.notifaano.ir/api";
		}
		return url;
	}
}
