/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class BaseModelElectronicEquipmentInsuranceBuilder {
    //the instance to build
    private BaseModelElectronicEquipmentInsurance baseModelElectronicEquipmentInsurance;

    /**
     * Default constructor to initialize the instance
     */
    public BaseModelElectronicEquipmentInsuranceBuilder() {
        baseModelElectronicEquipmentInsurance = new BaseModelElectronicEquipmentInsurance();
    }

    public BaseModelElectronicEquipmentInsuranceBuilder isSuccess(boolean isSuccess) {
        baseModelElectronicEquipmentInsurance.setIsSuccess(isSuccess);
        return this;
    }

    public BaseModelElectronicEquipmentInsuranceBuilder status(int status) {
        baseModelElectronicEquipmentInsurance.setStatus(status);
        return this;
    }

    public BaseModelElectronicEquipmentInsuranceBuilder message(ElectronicEquipmentInsurance message) {
        baseModelElectronicEquipmentInsurance.setMessage(message);
        return this;
    }

    public BaseModelElectronicEquipmentInsuranceBuilder extraData(String extraData) {
        baseModelElectronicEquipmentInsurance.setExtraData(extraData);
        return this;
    }

    public BaseModelElectronicEquipmentInsuranceBuilder exception(String exception) {
        baseModelElectronicEquipmentInsurance.setException(exception);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BaseModelElectronicEquipmentInsurance build() {
        return baseModelElectronicEquipmentInsurance;
    }
}