/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class BaseModelTravelInsuranceBuilder {
    //the instance to build
    private BaseModelTravelInsurance baseModelTravelInsurance;

    /**
     * Default constructor to initialize the instance
     */
    public BaseModelTravelInsuranceBuilder() {
        baseModelTravelInsurance = new BaseModelTravelInsurance();
    }

    public BaseModelTravelInsuranceBuilder isSuccess(boolean isSuccess) {
        baseModelTravelInsurance.setIsSuccess(isSuccess);
        return this;
    }

    public BaseModelTravelInsuranceBuilder status(int status) {
        baseModelTravelInsurance.setStatus(status);
        return this;
    }

    public BaseModelTravelInsuranceBuilder message(TravelInsurance message) {
        baseModelTravelInsurance.setMessage(message);
        return this;
    }

    public BaseModelTravelInsuranceBuilder extraData(String extraData) {
        baseModelTravelInsurance.setExtraData(extraData);
        return this;
    }

    public BaseModelTravelInsuranceBuilder exception(String exception) {
        baseModelTravelInsurance.setException(exception);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BaseModelTravelInsurance build() {
        return baseModelTravelInsurance;
    }
}