/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class BaseModelPortalLandingPageBuilder {
    //the instance to build
    private BaseModelPortalLandingPage baseModelPortalLandingPage;

    /**
     * Default constructor to initialize the instance
     */
    public BaseModelPortalLandingPageBuilder() {
        baseModelPortalLandingPage = new BaseModelPortalLandingPage();
    }

    public BaseModelPortalLandingPageBuilder isSuccess(boolean isSuccess) {
        baseModelPortalLandingPage.setIsSuccess(isSuccess);
        return this;
    }

    public BaseModelPortalLandingPageBuilder status(int status) {
        baseModelPortalLandingPage.setStatus(status);
        return this;
    }

    public BaseModelPortalLandingPageBuilder message(PortalLandingPage message) {
        baseModelPortalLandingPage.setMessage(message);
        return this;
    }

    public BaseModelPortalLandingPageBuilder extraData(ExtraDataBaseModelPortalLandingPage extraData) {
        baseModelPortalLandingPage.setExtraData(extraData);
        return this;
    }

    public BaseModelPortalLandingPageBuilder exception(String exception) {
        baseModelPortalLandingPage.setException(exception);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public BaseModelPortalLandingPage build() {
        return baseModelPortalLandingPage;
    }
}