/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class CarBrandTipsModelBuilder {
    //the instance to build
    private CarBrandTipsModel carBrandTipsModel;

    /**
     * Default constructor to initialize the instance
     */
    public CarBrandTipsModelBuilder() {
        carBrandTipsModel = new CarBrandTipsModel();
    }

    public CarBrandTipsModelBuilder id(int id) {
        carBrandTipsModel.setId(id);
        return this;
    }

    public CarBrandTipsModelBuilder title(String title) {
        carBrandTipsModel.setTitle(title);
        return this;
    }

    public CarBrandTipsModelBuilder extraData(int extraData) {
        carBrandTipsModel.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CarBrandTipsModel build() {
        return carBrandTipsModel;
    }
}