/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class ComboDataModelBuilder {
    //the instance to build
    private ComboDataModel comboDataModel;

    /**
     * Default constructor to initialize the instance
     */
    public ComboDataModelBuilder() {
        comboDataModel = new ComboDataModel();
    }

    public ComboDataModelBuilder id(int id) {
        comboDataModel.setId(id);
        return this;
    }

    /**
     * عنوان
     */
    public ComboDataModelBuilder title(String title) {
        comboDataModel.setTitle(title);
        return this;
    }

    /**
     * اطلاعات اضافه
     */
    public ComboDataModelBuilder extraData(String extraData) {
        comboDataModel.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ComboDataModel build() {
        return comboDataModel;
    }
}