/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class DeviceTypeBuilder {
    //the instance to build
    private DeviceType deviceType;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceTypeBuilder() {
        deviceType = new DeviceType();
    }

    public DeviceTypeBuilder id(int id) {
        deviceType.setId(id);
        return this;
    }

    public DeviceTypeBuilder title(String title) {
        deviceType.setTitle(title);
        return this;
    }

    public DeviceTypeBuilder extraData(String extraData) {
        deviceType.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceType build() {
        return deviceType;
    }
}