/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ElectronicEquipmentInsurancePolicyFilter 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5378380427466918874L;
    private Integer deviceTypeId;
    private Integer deviceBrandId;
    private Integer deviceModelId;
    private String buildYear;
    private String deviceValue;
    private Integer franchiseeId;
    private Integer insuranceExtraCoverageIds;
    private Integer policyTermId;
    private String insuranceCentreSubDomainName;
    private Integer insuranceCentreId;
    private Integer insuranceCompanyId;
    private boolean isSearchQuery;
    private String giftCode;
    private Integer customerUserId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceTypeId")
    public Integer getDeviceTypeId ( ) { 
        return this.deviceTypeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceTypeId")
    public void setDeviceTypeId (Integer value) { 
        this.deviceTypeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceBrandId")
    public Integer getDeviceBrandId ( ) { 
        return this.deviceBrandId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceBrandId")
    public void setDeviceBrandId (Integer value) { 
        this.deviceBrandId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceModelId")
    public Integer getDeviceModelId ( ) { 
        return this.deviceModelId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceModelId")
    public void setDeviceModelId (Integer value) { 
        this.deviceModelId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("buildYear")
    public String getBuildYear ( ) { 
        return this.buildYear;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("buildYear")
    public void setBuildYear (String value) { 
        this.buildYear = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceValue")
    public String getDeviceValue ( ) { 
        return this.deviceValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceValue")
    public void setDeviceValue (String value) { 
        this.deviceValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("franchiseeId")
    public Integer getFranchiseeId ( ) { 
        return this.franchiseeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("franchiseeId")
    public void setFranchiseeId (Integer value) { 
        this.franchiseeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceExtraCoverageIds")
    public Integer getInsuranceExtraCoverageIds ( ) { 
        return this.insuranceExtraCoverageIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceExtraCoverageIds")
    public void setInsuranceExtraCoverageIds (Integer value) { 
        this.insuranceExtraCoverageIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("policyTermId")
    public Integer getPolicyTermId ( ) { 
        return this.policyTermId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("policyTermId")
    public void setPolicyTermId (Integer value) { 
        this.policyTermId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreSubDomainName")
    public String getInsuranceCentreSubDomainName ( ) { 
        return this.insuranceCentreSubDomainName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreSubDomainName")
    public void setInsuranceCentreSubDomainName (String value) { 
        this.insuranceCentreSubDomainName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreId")
    public Integer getInsuranceCentreId ( ) { 
        return this.insuranceCentreId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreId")
    public void setInsuranceCentreId (Integer value) { 
        this.insuranceCentreId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyId")
    public Integer getInsuranceCompanyId ( ) { 
        return this.insuranceCompanyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyId")
    public void setInsuranceCompanyId (Integer value) { 
        this.insuranceCompanyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isSearchQuery")
    public boolean getIsSearchQuery ( ) { 
        return this.isSearchQuery;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isSearchQuery")
    public void setIsSearchQuery (boolean value) { 
        this.isSearchQuery = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("giftCode")
    public String getGiftCode ( ) { 
        return this.giftCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("giftCode")
    public void setGiftCode (String value) { 
        this.giftCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customerUserId")
    public Integer getCustomerUserId ( ) { 
        return this.customerUserId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customerUserId")
    public void setCustomerUserId (Integer value) { 
        this.customerUserId = value;
    }
 
}
