/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ElectronicEquipmentInsurancePolicyExtendView 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2902393987066862683L;
    private Integer deviceTypeId;
    private Integer deviceBrandId;
    private Integer deviceModelId;
    private String deviceSerial;
    private String buildYear;
    private Integer deviceValue;
    private Integer franchisee;
    private Boolean hasWarranty;
    private String warrantyCompany;
    private String serialInsuranceCard;
    private Long metaMediaBehindDeviceId;
    private String metaMediaBehindDeviceUrl;
    private Long metaMediaOnDeviceId;
    private String metaMediaOnDeviceUrl;
    private Long metaMediaDeviceBoxId;
    private String metaMediaDeviceBoxUrl;
    private String insuranceCoverageIds;
    private String insuranceCoveragePrice;
    private String basePremium;
    private String allPremium;
    private String insuranceCompanyDiscountRate;
    private int insuranceCompanyDiscount;
    private int insuranceCentreDiscount;
    private int coupenDiscount;
    private int allDiscount;
    private int exchangePremium;
    private String deviceTypeTitle;
    private String deviceBrandTitle;
    private String deviceModelTitle;
    /** GETTER
     * شناسه ی نوع دستگاه
     */
    @JsonGetter("deviceTypeId")
    public Integer getDeviceTypeId ( ) { 
        return this.deviceTypeId;
    }
    
    /** SETTER
     * شناسه ی نوع دستگاه
     */
    @JsonSetter("deviceTypeId")
    public void setDeviceTypeId (Integer value) { 
        this.deviceTypeId = value;
    }
 
    /** GETTER
     * شناسه ی برند دستگاه
     */
    @JsonGetter("deviceBrandId")
    public Integer getDeviceBrandId ( ) { 
        return this.deviceBrandId;
    }
    
    /** SETTER
     * شناسه ی برند دستگاه
     */
    @JsonSetter("deviceBrandId")
    public void setDeviceBrandId (Integer value) { 
        this.deviceBrandId = value;
    }
 
    /** GETTER
     * شناسه ی مدل دستگاه
     */
    @JsonGetter("deviceModelId")
    public Integer getDeviceModelId ( ) { 
        return this.deviceModelId;
    }
    
    /** SETTER
     * شناسه ی مدل دستگاه
     */
    @JsonSetter("deviceModelId")
    public void setDeviceModelId (Integer value) { 
        this.deviceModelId = value;
    }
 
    /** GETTER
     * سریال دستگاه
     */
    @JsonGetter("deviceSerial")
    public String getDeviceSerial ( ) { 
        return this.deviceSerial;
    }
    
    /** SETTER
     * سریال دستگاه
     */
    @JsonSetter("deviceSerial")
    public void setDeviceSerial (String value) { 
        this.deviceSerial = value;
    }
 
    /** GETTER
     * سال ساخت دستگاه
     */
    @JsonGetter("buildYear")
    public String getBuildYear ( ) { 
        return this.buildYear;
    }
    
    /** SETTER
     * سال ساخت دستگاه
     */
    @JsonSetter("buildYear")
    public void setBuildYear (String value) { 
        this.buildYear = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceValue")
    public Integer getDeviceValue ( ) { 
        return this.deviceValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceValue")
    public void setDeviceValue (Integer value) { 
        this.deviceValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("franchisee")
    public Integer getFranchisee ( ) { 
        return this.franchisee;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("franchisee")
    public void setFranchisee (Integer value) { 
        this.franchisee = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasWarranty")
    public Boolean getHasWarranty ( ) { 
        return this.hasWarranty;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasWarranty")
    public void setHasWarranty (Boolean value) { 
        this.hasWarranty = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("warrantyCompany")
    public String getWarrantyCompany ( ) { 
        return this.warrantyCompany;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("warrantyCompany")
    public void setWarrantyCompany (String value) { 
        this.warrantyCompany = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("serialInsuranceCard")
    public String getSerialInsuranceCard ( ) { 
        return this.serialInsuranceCard;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("serialInsuranceCard")
    public void setSerialInsuranceCard (String value) { 
        this.serialInsuranceCard = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaBehindDeviceId")
    public Long getMetaMediaBehindDeviceId ( ) { 
        return this.metaMediaBehindDeviceId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaBehindDeviceId")
    public void setMetaMediaBehindDeviceId (Long value) { 
        this.metaMediaBehindDeviceId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaBehindDeviceUrl")
    public String getMetaMediaBehindDeviceUrl ( ) { 
        return this.metaMediaBehindDeviceUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaBehindDeviceUrl")
    public void setMetaMediaBehindDeviceUrl (String value) { 
        this.metaMediaBehindDeviceUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaOnDeviceId")
    public Long getMetaMediaOnDeviceId ( ) { 
        return this.metaMediaOnDeviceId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaOnDeviceId")
    public void setMetaMediaOnDeviceId (Long value) { 
        this.metaMediaOnDeviceId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaOnDeviceUrl")
    public String getMetaMediaOnDeviceUrl ( ) { 
        return this.metaMediaOnDeviceUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaOnDeviceUrl")
    public void setMetaMediaOnDeviceUrl (String value) { 
        this.metaMediaOnDeviceUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaDeviceBoxId")
    public Long getMetaMediaDeviceBoxId ( ) { 
        return this.metaMediaDeviceBoxId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaDeviceBoxId")
    public void setMetaMediaDeviceBoxId (Long value) { 
        this.metaMediaDeviceBoxId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaDeviceBoxUrl")
    public String getMetaMediaDeviceBoxUrl ( ) { 
        return this.metaMediaDeviceBoxUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaDeviceBoxUrl")
    public void setMetaMediaDeviceBoxUrl (String value) { 
        this.metaMediaDeviceBoxUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("_InsuranceCoverageIds")
    public String getInsuranceCoverageIds ( ) { 
        return this.insuranceCoverageIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("_InsuranceCoverageIds")
    public void setInsuranceCoverageIds (String value) { 
        this.insuranceCoverageIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCoveragePrice")
    public String getInsuranceCoveragePrice ( ) { 
        return this.insuranceCoveragePrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCoveragePrice")
    public void setInsuranceCoveragePrice (String value) { 
        this.insuranceCoveragePrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("basePremium")
    public String getBasePremium ( ) { 
        return this.basePremium;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("basePremium")
    public void setBasePremium (String value) { 
        this.basePremium = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("allPremium")
    public String getAllPremium ( ) { 
        return this.allPremium;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("allPremium")
    public void setAllPremium (String value) { 
        this.allPremium = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyDiscountRate")
    public String getInsuranceCompanyDiscountRate ( ) { 
        return this.insuranceCompanyDiscountRate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyDiscountRate")
    public void setInsuranceCompanyDiscountRate (String value) { 
        this.insuranceCompanyDiscountRate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyDiscount")
    public int getInsuranceCompanyDiscount ( ) { 
        return this.insuranceCompanyDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyDiscount")
    public void setInsuranceCompanyDiscount (int value) { 
        this.insuranceCompanyDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreDiscount")
    public int getInsuranceCentreDiscount ( ) { 
        return this.insuranceCentreDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreDiscount")
    public void setInsuranceCentreDiscount (int value) { 
        this.insuranceCentreDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coupenDiscount")
    public int getCoupenDiscount ( ) { 
        return this.coupenDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coupenDiscount")
    public void setCoupenDiscount (int value) { 
        this.coupenDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("allDiscount")
    public int getAllDiscount ( ) { 
        return this.allDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("allDiscount")
    public void setAllDiscount (int value) { 
        this.allDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exchangePremium")
    public int getExchangePremium ( ) { 
        return this.exchangePremium;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exchangePremium")
    public void setExchangePremium (int value) { 
        this.exchangePremium = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceTypeTitle")
    public String getDeviceTypeTitle ( ) { 
        return this.deviceTypeTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceTypeTitle")
    public void setDeviceTypeTitle (String value) { 
        this.deviceTypeTitle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceBrandTitle")
    public String getDeviceBrandTitle ( ) { 
        return this.deviceBrandTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceBrandTitle")
    public void setDeviceBrandTitle (String value) { 
        this.deviceBrandTitle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceModelTitle")
    public String getDeviceModelTitle ( ) { 
        return this.deviceModelTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceModelTitle")
    public void setDeviceModelTitle (String value) { 
        this.deviceModelTitle = value;
    }
 
}
