/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class ElectronicEquipmentInsurancePolicyExtendViewBuilder {
    //the instance to build
    private ElectronicEquipmentInsurancePolicyExtendView electronicEquipmentInsurancePolicyExtendView;

    /**
     * Default constructor to initialize the instance
     */
    public ElectronicEquipmentInsurancePolicyExtendViewBuilder() {
        electronicEquipmentInsurancePolicyExtendView = new ElectronicEquipmentInsurancePolicyExtendView();
    }

    /**
     * شناسه ی نوع دستگاه
     */
    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceTypeId(Integer deviceTypeId) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceTypeId(deviceTypeId);
        return this;
    }

    /**
     * شناسه ی برند دستگاه
     */
    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceBrandId(Integer deviceBrandId) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceBrandId(deviceBrandId);
        return this;
    }

    /**
     * شناسه ی مدل دستگاه
     */
    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceModelId(Integer deviceModelId) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceModelId(deviceModelId);
        return this;
    }

    /**
     * سریال دستگاه
     */
    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceSerial(String deviceSerial) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceSerial(deviceSerial);
        return this;
    }

    /**
     * سال ساخت دستگاه
     */
    public ElectronicEquipmentInsurancePolicyExtendViewBuilder buildYear(String buildYear) {
        electronicEquipmentInsurancePolicyExtendView.setBuildYear(buildYear);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceValue(Integer deviceValue) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceValue(deviceValue);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder franchisee(Integer franchisee) {
        electronicEquipmentInsurancePolicyExtendView.setFranchisee(franchisee);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder hasWarranty(Boolean hasWarranty) {
        electronicEquipmentInsurancePolicyExtendView.setHasWarranty(hasWarranty);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder warrantyCompany(String warrantyCompany) {
        electronicEquipmentInsurancePolicyExtendView.setWarrantyCompany(warrantyCompany);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder serialInsuranceCard(String serialInsuranceCard) {
        electronicEquipmentInsurancePolicyExtendView.setSerialInsuranceCard(serialInsuranceCard);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder metaMediaBehindDeviceId(Long metaMediaBehindDeviceId) {
        electronicEquipmentInsurancePolicyExtendView.setMetaMediaBehindDeviceId(metaMediaBehindDeviceId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder metaMediaBehindDeviceUrl(String metaMediaBehindDeviceUrl) {
        electronicEquipmentInsurancePolicyExtendView.setMetaMediaBehindDeviceUrl(metaMediaBehindDeviceUrl);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder metaMediaOnDeviceId(Long metaMediaOnDeviceId) {
        electronicEquipmentInsurancePolicyExtendView.setMetaMediaOnDeviceId(metaMediaOnDeviceId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder metaMediaOnDeviceUrl(String metaMediaOnDeviceUrl) {
        electronicEquipmentInsurancePolicyExtendView.setMetaMediaOnDeviceUrl(metaMediaOnDeviceUrl);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder metaMediaDeviceBoxId(Long metaMediaDeviceBoxId) {
        electronicEquipmentInsurancePolicyExtendView.setMetaMediaDeviceBoxId(metaMediaDeviceBoxId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder metaMediaDeviceBoxUrl(String metaMediaDeviceBoxUrl) {
        electronicEquipmentInsurancePolicyExtendView.setMetaMediaDeviceBoxUrl(metaMediaDeviceBoxUrl);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder insuranceCoverageIds(String insuranceCoverageIds) {
        electronicEquipmentInsurancePolicyExtendView.setInsuranceCoverageIds(insuranceCoverageIds);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder insuranceCoveragePrice(String insuranceCoveragePrice) {
        electronicEquipmentInsurancePolicyExtendView.setInsuranceCoveragePrice(insuranceCoveragePrice);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder basePremium(String basePremium) {
        electronicEquipmentInsurancePolicyExtendView.setBasePremium(basePremium);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder allPremium(String allPremium) {
        electronicEquipmentInsurancePolicyExtendView.setAllPremium(allPremium);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder insuranceCompanyDiscountRate(String insuranceCompanyDiscountRate) {
        electronicEquipmentInsurancePolicyExtendView.setInsuranceCompanyDiscountRate(insuranceCompanyDiscountRate);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder insuranceCompanyDiscount(int insuranceCompanyDiscount) {
        electronicEquipmentInsurancePolicyExtendView.setInsuranceCompanyDiscount(insuranceCompanyDiscount);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder insuranceCentreDiscount(int insuranceCentreDiscount) {
        electronicEquipmentInsurancePolicyExtendView.setInsuranceCentreDiscount(insuranceCentreDiscount);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder coupenDiscount(int coupenDiscount) {
        electronicEquipmentInsurancePolicyExtendView.setCoupenDiscount(coupenDiscount);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder allDiscount(int allDiscount) {
        electronicEquipmentInsurancePolicyExtendView.setAllDiscount(allDiscount);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder exchangePremium(int exchangePremium) {
        electronicEquipmentInsurancePolicyExtendView.setExchangePremium(exchangePremium);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceTypeTitle(String deviceTypeTitle) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceTypeTitle(deviceTypeTitle);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceBrandTitle(String deviceBrandTitle) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceBrandTitle(deviceBrandTitle);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyExtendViewBuilder deviceModelTitle(String deviceModelTitle) {
        electronicEquipmentInsurancePolicyExtendView.setDeviceModelTitle(deviceModelTitle);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ElectronicEquipmentInsurancePolicyExtendView build() {
        return electronicEquipmentInsurancePolicyExtendView;
    }
}