/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class ElectronicEquipmentInsurancePolicyFilterBuilder {
    //the instance to build
    private ElectronicEquipmentInsurancePolicyFilter electronicEquipmentInsurancePolicyFilter;

    /**
     * Default constructor to initialize the instance
     */
    public ElectronicEquipmentInsurancePolicyFilterBuilder() {
        electronicEquipmentInsurancePolicyFilter = new ElectronicEquipmentInsurancePolicyFilter();
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder deviceTypeId(Integer deviceTypeId) {
        electronicEquipmentInsurancePolicyFilter.setDeviceTypeId(deviceTypeId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder deviceBrandId(Integer deviceBrandId) {
        electronicEquipmentInsurancePolicyFilter.setDeviceBrandId(deviceBrandId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder deviceModelId(Integer deviceModelId) {
        electronicEquipmentInsurancePolicyFilter.setDeviceModelId(deviceModelId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder buildYear(String buildYear) {
        electronicEquipmentInsurancePolicyFilter.setBuildYear(buildYear);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder deviceValue(String deviceValue) {
        electronicEquipmentInsurancePolicyFilter.setDeviceValue(deviceValue);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder franchiseeId(Integer franchiseeId) {
        electronicEquipmentInsurancePolicyFilter.setFranchiseeId(franchiseeId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder insuranceExtraCoverageIds(Integer insuranceExtraCoverageIds) {
        electronicEquipmentInsurancePolicyFilter.setInsuranceExtraCoverageIds(insuranceExtraCoverageIds);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder policyTermId(Integer policyTermId) {
        electronicEquipmentInsurancePolicyFilter.setPolicyTermId(policyTermId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder insuranceCentreSubDomainName(String insuranceCentreSubDomainName) {
        electronicEquipmentInsurancePolicyFilter.setInsuranceCentreSubDomainName(insuranceCentreSubDomainName);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder insuranceCentreId(Integer insuranceCentreId) {
        electronicEquipmentInsurancePolicyFilter.setInsuranceCentreId(insuranceCentreId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder insuranceCompanyId(Integer insuranceCompanyId) {
        electronicEquipmentInsurancePolicyFilter.setInsuranceCompanyId(insuranceCompanyId);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder isSearchQuery(boolean isSearchQuery) {
        electronicEquipmentInsurancePolicyFilter.setIsSearchQuery(isSearchQuery);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder giftCode(String giftCode) {
        electronicEquipmentInsurancePolicyFilter.setGiftCode(giftCode);
        return this;
    }

    public ElectronicEquipmentInsurancePolicyFilterBuilder customerUserId(Integer customerUserId) {
        electronicEquipmentInsurancePolicyFilter.setCustomerUserId(customerUserId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ElectronicEquipmentInsurancePolicyFilter build() {
        return electronicEquipmentInsurancePolicyFilter;
    }
}