/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ElevatorInsurancePolicyExtendView 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3119745023485469243L;
    private String buildingUseTypeParamId;
    private String elevatorTypeParamId;
    private String floors;
    private String elevatorCapacity;
    private String elevatorCapacityCargo;
    private String defectOrganCoverageId;
    private String deathCapitalCoverageId;
    private String financialCoverageId;
    private String medicalCostCoverageId;
    private String riskLevelDiscountRate;
    private String insuranceRiskLevelId;
    private String discountRate;
    private String cityId;
    private String provinceId;
    private String zipCode;
    private String addressPlaceBuilding;
    private boolean ownerCoverage;
    private int riskLevelDiscount;
    private String basePremium;
    private String allPremium;
    private int insuranceCompanyDiscountRate;
    private int insuranceCompanyDiscount;
    private int insuranceCentreDiscount;
    private int coupenDiscount;
    private int allDiscount;
    private int exchangePremium;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("buildingUseTypeParamId")
    public String getBuildingUseTypeParamId ( ) { 
        return this.buildingUseTypeParamId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("buildingUseTypeParamId")
    public void setBuildingUseTypeParamId (String value) { 
        this.buildingUseTypeParamId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("elevatorTypeParamId")
    public String getElevatorTypeParamId ( ) { 
        return this.elevatorTypeParamId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("elevatorTypeParamId")
    public void setElevatorTypeParamId (String value) { 
        this.elevatorTypeParamId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("floors")
    public String getFloors ( ) { 
        return this.floors;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("floors")
    public void setFloors (String value) { 
        this.floors = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("elevatorCapacity")
    public String getElevatorCapacity ( ) { 
        return this.elevatorCapacity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("elevatorCapacity")
    public void setElevatorCapacity (String value) { 
        this.elevatorCapacity = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("elevatorCapacityCargo")
    public String getElevatorCapacityCargo ( ) { 
        return this.elevatorCapacityCargo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("elevatorCapacityCargo")
    public void setElevatorCapacityCargo (String value) { 
        this.elevatorCapacityCargo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("defectOrganCoverageId")
    public String getDefectOrganCoverageId ( ) { 
        return this.defectOrganCoverageId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("defectOrganCoverageId")
    public void setDefectOrganCoverageId (String value) { 
        this.defectOrganCoverageId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deathCapitalCoverageId")
    public String getDeathCapitalCoverageId ( ) { 
        return this.deathCapitalCoverageId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deathCapitalCoverageId")
    public void setDeathCapitalCoverageId (String value) { 
        this.deathCapitalCoverageId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("financialCoverageId")
    public String getFinancialCoverageId ( ) { 
        return this.financialCoverageId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("financialCoverageId")
    public void setFinancialCoverageId (String value) { 
        this.financialCoverageId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("medicalCostCoverageId")
    public String getMedicalCostCoverageId ( ) { 
        return this.medicalCostCoverageId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("medicalCostCoverageId")
    public void setMedicalCostCoverageId (String value) { 
        this.medicalCostCoverageId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("riskLevelDiscountRate")
    public String getRiskLevelDiscountRate ( ) { 
        return this.riskLevelDiscountRate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("riskLevelDiscountRate")
    public void setRiskLevelDiscountRate (String value) { 
        this.riskLevelDiscountRate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceRiskLevelId")
    public String getInsuranceRiskLevelId ( ) { 
        return this.insuranceRiskLevelId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceRiskLevelId")
    public void setInsuranceRiskLevelId (String value) { 
        this.insuranceRiskLevelId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("discountRate")
    public String getDiscountRate ( ) { 
        return this.discountRate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("discountRate")
    public void setDiscountRate (String value) { 
        this.discountRate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cityId")
    public String getCityId ( ) { 
        return this.cityId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cityId")
    public void setCityId (String value) { 
        this.cityId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("provinceId")
    public String getProvinceId ( ) { 
        return this.provinceId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("provinceId")
    public void setProvinceId (String value) { 
        this.provinceId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("zipCode")
    public String getZipCode ( ) { 
        return this.zipCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("zipCode")
    public void setZipCode (String value) { 
        this.zipCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("addressPlaceBuilding")
    public String getAddressPlaceBuilding ( ) { 
        return this.addressPlaceBuilding;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("addressPlaceBuilding")
    public void setAddressPlaceBuilding (String value) { 
        this.addressPlaceBuilding = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ownerCoverage")
    public boolean getOwnerCoverage ( ) { 
        return this.ownerCoverage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ownerCoverage")
    public void setOwnerCoverage (boolean value) { 
        this.ownerCoverage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("riskLevelDiscount")
    public int getRiskLevelDiscount ( ) { 
        return this.riskLevelDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("riskLevelDiscount")
    public void setRiskLevelDiscount (int value) { 
        this.riskLevelDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("basePremium")
    public String getBasePremium ( ) { 
        return this.basePremium;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("basePremium")
    public void setBasePremium (String value) { 
        this.basePremium = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("allPremium")
    public String getAllPremium ( ) { 
        return this.allPremium;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("allPremium")
    public void setAllPremium (String value) { 
        this.allPremium = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyDiscountRate")
    public int getInsuranceCompanyDiscountRate ( ) { 
        return this.insuranceCompanyDiscountRate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyDiscountRate")
    public void setInsuranceCompanyDiscountRate (int value) { 
        this.insuranceCompanyDiscountRate = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyDiscount")
    public int getInsuranceCompanyDiscount ( ) { 
        return this.insuranceCompanyDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyDiscount")
    public void setInsuranceCompanyDiscount (int value) { 
        this.insuranceCompanyDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreDiscount")
    public int getInsuranceCentreDiscount ( ) { 
        return this.insuranceCentreDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreDiscount")
    public void setInsuranceCentreDiscount (int value) { 
        this.insuranceCentreDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coupenDiscount")
    public int getCoupenDiscount ( ) { 
        return this.coupenDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coupenDiscount")
    public void setCoupenDiscount (int value) { 
        this.coupenDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("allDiscount")
    public int getAllDiscount ( ) { 
        return this.allDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("allDiscount")
    public void setAllDiscount (int value) { 
        this.allDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exchangePremium")
    public int getExchangePremium ( ) { 
        return this.exchangePremium;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exchangePremium")
    public void setExchangePremium (int value) { 
        this.exchangePremium = value;
    }
 
}
