/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class ElevatorInsurancePolicyFilterBuilder {
    //the instance to build
    private ElevatorInsurancePolicyFilter elevatorInsurancePolicyFilter;

    /**
     * Default constructor to initialize the instance
     */
    public ElevatorInsurancePolicyFilterBuilder() {
        elevatorInsurancePolicyFilter = new ElevatorInsurancePolicyFilter();
    }

    public ElevatorInsurancePolicyFilterBuilder buildingUseTypeParamId(String buildingUseTypeParamId) {
        elevatorInsurancePolicyFilter.setBuildingUseTypeParamId(buildingUseTypeParamId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder elevatorTypeParamId(String elevatorTypeParamId) {
        elevatorInsurancePolicyFilter.setElevatorTypeParamId(elevatorTypeParamId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder floors(String floors) {
        elevatorInsurancePolicyFilter.setFloors(floors);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder elevatorCapacityCargo(String elevatorCapacityCargo) {
        elevatorInsurancePolicyFilter.setElevatorCapacityCargo(elevatorCapacityCargo);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder elevatorCapacity(String elevatorCapacity) {
        elevatorInsurancePolicyFilter.setElevatorCapacity(elevatorCapacity);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder riskLevelId(String riskLevelId) {
        elevatorInsurancePolicyFilter.setRiskLevelId(riskLevelId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder insurancePolicyTerms(String insurancePolicyTerms) {
        elevatorInsurancePolicyFilter.setInsurancePolicyTerms(insurancePolicyTerms);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder defectOrganCoverageId(String defectOrganCoverageId) {
        elevatorInsurancePolicyFilter.setDefectOrganCoverageId(defectOrganCoverageId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder deathCapitalCoverageId(String deathCapitalCoverageId) {
        elevatorInsurancePolicyFilter.setDeathCapitalCoverageId(deathCapitalCoverageId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder financialCoverageId(String financialCoverageId) {
        elevatorInsurancePolicyFilter.setFinancialCoverageId(financialCoverageId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder medicalCostCoverageId(String medicalCostCoverageId) {
        elevatorInsurancePolicyFilter.setMedicalCostCoverageId(medicalCostCoverageId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder ownerCoverage(boolean ownerCoverage) {
        elevatorInsurancePolicyFilter.setOwnerCoverage(ownerCoverage);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder insuranceExtraCoverageIds(String insuranceExtraCoverageIds) {
        elevatorInsurancePolicyFilter.setInsuranceExtraCoverageIds(insuranceExtraCoverageIds);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder policyTermId(String policyTermId) {
        elevatorInsurancePolicyFilter.setPolicyTermId(policyTermId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder insuranceCentreSubDomainName(String insuranceCentreSubDomainName) {
        elevatorInsurancePolicyFilter.setInsuranceCentreSubDomainName(insuranceCentreSubDomainName);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder insuranceCentreId(String insuranceCentreId) {
        elevatorInsurancePolicyFilter.setInsuranceCentreId(insuranceCentreId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder insuranceCompanyId(String insuranceCompanyId) {
        elevatorInsurancePolicyFilter.setInsuranceCompanyId(insuranceCompanyId);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder isSearchQuery(boolean isSearchQuery) {
        elevatorInsurancePolicyFilter.setIsSearchQuery(isSearchQuery);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder giftCode(String giftCode) {
        elevatorInsurancePolicyFilter.setGiftCode(giftCode);
        return this;
    }

    public ElevatorInsurancePolicyFilterBuilder customerUserId(String customerUserId) {
        elevatorInsurancePolicyFilter.setCustomerUserId(customerUserId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ElevatorInsurancePolicyFilter build() {
        return elevatorInsurancePolicyFilter;
    }
}