/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ElevatorInsurance 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4445990984422275725L;
    private boolean hasPlan;
    private List<ComboDataModel> buildingUseTypes;
    private List<ElevatorType> elevatorTypes;
    private List<DefectOrganCoverage> defectOrganCoverage;
    private List<DeathCapitalCoverage> deathCapitalCoverage;
    private List<FinancialCoverage> financialCoverage;
    private List<MedicalCostCoverage> medicalCostCoverage;
    private List<InsuranceRiskLevel> insuranceRiskLevels;
    private List<InsurancePolicyTerm> insurancePolicyTerms;
    private List<InsuranceCompany> insuranceCompanies;
    private List<Province> provinces;
    private List<String> cities;
    private List<String> cityRegions;
    private List<ShippingType> shippingTypes;
    private List<PostType> postTypes;
    private InsurancePolicyCondition insurancePolicyCondition;
    private InsuranceDataElevatorInsurance insuranceData;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasPlan")
    public boolean getHasPlan ( ) { 
        return this.hasPlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasPlan")
    public void setHasPlan (boolean value) { 
        this.hasPlan = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("buildingUseTypes")
    public List<ComboDataModel> getBuildingUseTypes ( ) { 
        return this.buildingUseTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("buildingUseTypes")
    public void setBuildingUseTypes (List<ComboDataModel> value) { 
        this.buildingUseTypes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("elevatorTypes")
    public List<ElevatorType> getElevatorTypes ( ) { 
        return this.elevatorTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("elevatorTypes")
    public void setElevatorTypes (List<ElevatorType> value) { 
        this.elevatorTypes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("defectOrganCoverage")
    public List<DefectOrganCoverage> getDefectOrganCoverage ( ) { 
        return this.defectOrganCoverage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("defectOrganCoverage")
    public void setDefectOrganCoverage (List<DefectOrganCoverage> value) { 
        this.defectOrganCoverage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deathCapitalCoverage")
    public List<DeathCapitalCoverage> getDeathCapitalCoverage ( ) { 
        return this.deathCapitalCoverage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deathCapitalCoverage")
    public void setDeathCapitalCoverage (List<DeathCapitalCoverage> value) { 
        this.deathCapitalCoverage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("financialCoverage")
    public List<FinancialCoverage> getFinancialCoverage ( ) { 
        return this.financialCoverage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("financialCoverage")
    public void setFinancialCoverage (List<FinancialCoverage> value) { 
        this.financialCoverage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("medicalCostCoverage")
    public List<MedicalCostCoverage> getMedicalCostCoverage ( ) { 
        return this.medicalCostCoverage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("medicalCostCoverage")
    public void setMedicalCostCoverage (List<MedicalCostCoverage> value) { 
        this.medicalCostCoverage = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceRiskLevels")
    public List<InsuranceRiskLevel> getInsuranceRiskLevels ( ) { 
        return this.insuranceRiskLevels;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceRiskLevels")
    public void setInsuranceRiskLevels (List<InsuranceRiskLevel> value) { 
        this.insuranceRiskLevels = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyTerms")
    public List<InsurancePolicyTerm> getInsurancePolicyTerms ( ) { 
        return this.insurancePolicyTerms;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyTerms")
    public void setInsurancePolicyTerms (List<InsurancePolicyTerm> value) { 
        this.insurancePolicyTerms = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanies")
    public List<InsuranceCompany> getInsuranceCompanies ( ) { 
        return this.insuranceCompanies;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanies")
    public void setInsuranceCompanies (List<InsuranceCompany> value) { 
        this.insuranceCompanies = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("provinces")
    public List<Province> getProvinces ( ) { 
        return this.provinces;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("provinces")
    public void setProvinces (List<Province> value) { 
        this.provinces = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cities")
    public List<String> getCities ( ) { 
        return this.cities;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cities")
    public void setCities (List<String> value) { 
        this.cities = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cityRegions")
    public List<String> getCityRegions ( ) { 
        return this.cityRegions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cityRegions")
    public void setCityRegions (List<String> value) { 
        this.cityRegions = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shippingTypes")
    public List<ShippingType> getShippingTypes ( ) { 
        return this.shippingTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shippingTypes")
    public void setShippingTypes (List<ShippingType> value) { 
        this.shippingTypes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("postTypes")
    public List<PostType> getPostTypes ( ) { 
        return this.postTypes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("postTypes")
    public void setPostTypes (List<PostType> value) { 
        this.postTypes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyCondition")
    public InsurancePolicyCondition getInsurancePolicyCondition ( ) { 
        return this.insurancePolicyCondition;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyCondition")
    public void setInsurancePolicyCondition (InsurancePolicyCondition value) { 
        this.insurancePolicyCondition = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceData")
    public InsuranceDataElevatorInsurance getInsuranceData ( ) { 
        return this.insuranceData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceData")
    public void setInsuranceData (InsuranceDataElevatorInsurance value) { 
        this.insuranceData = value;
    }
 
}
