/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class EverySquareMeterCoverage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6013939856518407163L;
    private int id;
    private int fiscalYearId;
    private int insuranceCoverageId;
    private int coverageRial;
    private String coverageEuro;
    private String fromPrice;
    private String toPrice;
    private String isDiscount;
    private String coverageValueType;
    private String coverageStringValue;
    private String insuranceTypeIds;
    private String insuranceCompanyIds;
    private boolean selected;
    private String isVisible;
    private String insuranceTypeId;
    private String insurancePlansIds;
    private String isActive;
    private String insuranceTypeTitles;
    private String insuranceCompanyTitles;
    private String insurancePlanTitles;
    private String insuranceTypeTitle;
    private String createdBy;
    private String isPlan;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fiscalYearId")
    public int getFiscalYearId ( ) { 
        return this.fiscalYearId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fiscalYearId")
    public void setFiscalYearId (int value) { 
        this.fiscalYearId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCoverageId")
    public int getInsuranceCoverageId ( ) { 
        return this.insuranceCoverageId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCoverageId")
    public void setInsuranceCoverageId (int value) { 
        this.insuranceCoverageId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coverageRial")
    public int getCoverageRial ( ) { 
        return this.coverageRial;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coverageRial")
    public void setCoverageRial (int value) { 
        this.coverageRial = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coverageEuro")
    public String getCoverageEuro ( ) { 
        return this.coverageEuro;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coverageEuro")
    public void setCoverageEuro (String value) { 
        this.coverageEuro = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fromPrice")
    public String getFromPrice ( ) { 
        return this.fromPrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fromPrice")
    public void setFromPrice (String value) { 
        this.fromPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("toPrice")
    public String getToPrice ( ) { 
        return this.toPrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("toPrice")
    public void setToPrice (String value) { 
        this.toPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isDiscount")
    public String getIsDiscount ( ) { 
        return this.isDiscount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isDiscount")
    public void setIsDiscount (String value) { 
        this.isDiscount = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coverageValueType")
    public String getCoverageValueType ( ) { 
        return this.coverageValueType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coverageValueType")
    public void setCoverageValueType (String value) { 
        this.coverageValueType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("coverageStringValue")
    public String getCoverageStringValue ( ) { 
        return this.coverageStringValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("coverageStringValue")
    public void setCoverageStringValue (String value) { 
        this.coverageStringValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypeIds")
    public String getInsuranceTypeIds ( ) { 
        return this.insuranceTypeIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypeIds")
    public void setInsuranceTypeIds (String value) { 
        this.insuranceTypeIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyIds")
    public String getInsuranceCompanyIds ( ) { 
        return this.insuranceCompanyIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyIds")
    public void setInsuranceCompanyIds (String value) { 
        this.insuranceCompanyIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("selected")
    public boolean getSelected ( ) { 
        return this.selected;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("selected")
    public void setSelected (boolean value) { 
        this.selected = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isVisible")
    public String getIsVisible ( ) { 
        return this.isVisible;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isVisible")
    public void setIsVisible (String value) { 
        this.isVisible = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypeId")
    public String getInsuranceTypeId ( ) { 
        return this.insuranceTypeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypeId")
    public void setInsuranceTypeId (String value) { 
        this.insuranceTypeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePlansIds")
    public String getInsurancePlansIds ( ) { 
        return this.insurancePlansIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePlansIds")
    public void setInsurancePlansIds (String value) { 
        this.insurancePlansIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isActive")
    public String getIsActive ( ) { 
        return this.isActive;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isActive")
    public void setIsActive (String value) { 
        this.isActive = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypeTitles")
    public String getInsuranceTypeTitles ( ) { 
        return this.insuranceTypeTitles;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypeTitles")
    public void setInsuranceTypeTitles (String value) { 
        this.insuranceTypeTitles = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyTitles")
    public String getInsuranceCompanyTitles ( ) { 
        return this.insuranceCompanyTitles;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyTitles")
    public void setInsuranceCompanyTitles (String value) { 
        this.insuranceCompanyTitles = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePlanTitles")
    public String getInsurancePlanTitles ( ) { 
        return this.insurancePlanTitles;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePlanTitles")
    public void setInsurancePlanTitles (String value) { 
        this.insurancePlanTitles = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypeTitle")
    public String getInsuranceTypeTitle ( ) { 
        return this.insuranceTypeTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypeTitle")
    public void setInsuranceTypeTitle (String value) { 
        this.insuranceTypeTitle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("createdBy")
    public String getCreatedBy ( ) { 
        return this.createdBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("createdBy")
    public void setCreatedBy (String value) { 
        this.createdBy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isPlan")
    public String getIsPlan ( ) { 
        return this.isPlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isPlan")
    public void setIsPlan (String value) { 
        this.isPlan = value;
    }
 
}
