/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class ExceptionBuilder {
    //the instance to build
    private Exception exception;

    /**
     * Default constructor to initialize the instance
     */
    public ExceptionBuilder() {
        exception = new Exception();
    }

    public ExceptionBuilder dateTime(String dateTime) {
        exception.setDateTime(dateTime);
        return this;
    }

    public ExceptionBuilder message(String message) {
        exception.setMessage(message);
        return this;
    }

    public ExceptionBuilder helpLink(String helpLink) {
        exception.setHelpLink(helpLink);
        return this;
    }

    public ExceptionBuilder source(String source) {
        exception.setSource(source);
        return this;
    }

    public ExceptionBuilder stackTrace(String stackTrace) {
        exception.setStackTrace(stackTrace);
        return this;
    }

    public ExceptionBuilder targetSite(TargetSite targetSite) {
        exception.setTargetSite(targetSite);
        return this;
    }

    public ExceptionBuilder errorLine(String errorLine) {
        exception.setErrorLine(errorLine);
        return this;
    }

    public ExceptionBuilder exceptionType(String exceptionType) {
        exception.setExceptionType(exceptionType);
        return this;
    }

    public ExceptionBuilder exceptionUrl(String exceptionUrl) {
        exception.setExceptionUrl(exceptionUrl);
        return this;
    }

    public ExceptionBuilder innerException(String innerException) {
        exception.setInnerException(innerException);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Exception build() {
        return exception;
    }
}