/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Exception 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7954121372435972894L;
    private String dateTime;
    private String message;
    private String helpLink;
    private String source;
    private String stackTrace;
    private TargetSite targetSite;
    private String errorLine;
    private String exceptionType;
    private String exceptionUrl;
    private String innerException;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dateTime")
    public String getDateTime ( ) { 
        return this.dateTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dateTime")
    public void setDateTime (String value) { 
        this.dateTime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("message")
    public void setMessage (String value) { 
        this.message = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("helpLink")
    public String getHelpLink ( ) { 
        return this.helpLink;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("helpLink")
    public void setHelpLink (String value) { 
        this.helpLink = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("source")
    public String getSource ( ) { 
        return this.source;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("source")
    public void setSource (String value) { 
        this.source = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("stackTrace")
    public String getStackTrace ( ) { 
        return this.stackTrace;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("stackTrace")
    public void setStackTrace (String value) { 
        this.stackTrace = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("targetSite")
    public TargetSite getTargetSite ( ) { 
        return this.targetSite;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("targetSite")
    public void setTargetSite (TargetSite value) { 
        this.targetSite = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("errorLine")
    public String getErrorLine ( ) { 
        return this.errorLine;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("errorLine")
    public void setErrorLine (String value) { 
        this.errorLine = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exceptionType")
    public String getExceptionType ( ) { 
        return this.exceptionType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exceptionType")
    public void setExceptionType (String value) { 
        this.exceptionType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("exceptionUrl")
    public String getExceptionUrl ( ) { 
        return this.exceptionUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("exceptionUrl")
    public void setExceptionUrl (String value) { 
        this.exceptionUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("innerException")
    public String getInnerException ( ) { 
        return this.innerException;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("innerException")
    public void setInnerException (String value) { 
        this.innerException = value;
    }
 
}
