/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ExtraData 
        implements java.io.Serializable {
    private static final long serialVersionUID = -38200572779308111L;
    private String aliasName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("aliasName")
    public String getAliasName ( ) { 
        return this.aliasName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("aliasName")
    public void setAliasName (String value) { 
        this.aliasName = value;
    }
 
}
