/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ExtraDataBaseModelSpecialPlan 
        implements java.io.Serializable {
    private static final long serialVersionUID = 82802095114171373L;
    private int insuranceTypesCount;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypesCount")
    public int getInsuranceTypesCount ( ) { 
        return this.insuranceTypesCount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypesCount")
    public void setInsuranceTypesCount (int value) { 
        this.insuranceTypesCount = value;
    }
 
}
