/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class FinancialCoverageBuilder {
    //the instance to build
    private FinancialCoverage financialCoverage;

    /**
     * Default constructor to initialize the instance
     */
    public FinancialCoverageBuilder() {
        financialCoverage = new FinancialCoverage();
    }

    public FinancialCoverageBuilder id(int id) {
        financialCoverage.setId(id);
        return this;
    }

    public FinancialCoverageBuilder title(int title) {
        financialCoverage.setTitle(title);
        return this;
    }

    public FinancialCoverageBuilder extraData(String extraData) {
        financialCoverage.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FinancialCoverage build() {
        return financialCoverage;
    }
}