/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class FireInsurancePolicyFilter 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1135438264263522532L;
    private String insurancePolicyType;
    private String insuranceExtraCoverageIds;
    private String valuePerSquareMeterCoverageRateId;
    private String valueOfAppliancesFurnishing;
    private String cityId;
    private String skeletonTypeId;
    private int buildingTypeId;
    private String buildingArea;
    private String onlyAppliancesFurnishings;
    private String policyTermId;
    private String insuranceCentreSubDomainName;
    private String insuranceCentreId;
    private String insuranceCompanyId;
    private String giftCode;
    private String customerUserId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyType")
    public String getInsurancePolicyType ( ) { 
        return this.insurancePolicyType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyType")
    public void setInsurancePolicyType (String value) { 
        this.insurancePolicyType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceExtraCoverageIds")
    public String getInsuranceExtraCoverageIds ( ) { 
        return this.insuranceExtraCoverageIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceExtraCoverageIds")
    public void setInsuranceExtraCoverageIds (String value) { 
        this.insuranceExtraCoverageIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("valuePerSquareMeterCoverageRateId")
    public String getValuePerSquareMeterCoverageRateId ( ) { 
        return this.valuePerSquareMeterCoverageRateId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("valuePerSquareMeterCoverageRateId")
    public void setValuePerSquareMeterCoverageRateId (String value) { 
        this.valuePerSquareMeterCoverageRateId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("valueOfAppliancesFurnishing")
    public String getValueOfAppliancesFurnishing ( ) { 
        return this.valueOfAppliancesFurnishing;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("valueOfAppliancesFurnishing")
    public void setValueOfAppliancesFurnishing (String value) { 
        this.valueOfAppliancesFurnishing = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cityId")
    public String getCityId ( ) { 
        return this.cityId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cityId")
    public void setCityId (String value) { 
        this.cityId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("skeletonTypeId")
    public String getSkeletonTypeId ( ) { 
        return this.skeletonTypeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("skeletonTypeId")
    public void setSkeletonTypeId (String value) { 
        this.skeletonTypeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("buildingTypeId")
    public int getBuildingTypeId ( ) { 
        return this.buildingTypeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("buildingTypeId")
    public void setBuildingTypeId (int value) { 
        this.buildingTypeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("buildingArea")
    public String getBuildingArea ( ) { 
        return this.buildingArea;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("buildingArea")
    public void setBuildingArea (String value) { 
        this.buildingArea = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("onlyAppliancesFurnishings")
    public String getOnlyAppliancesFurnishings ( ) { 
        return this.onlyAppliancesFurnishings;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("onlyAppliancesFurnishings")
    public void setOnlyAppliancesFurnishings (String value) { 
        this.onlyAppliancesFurnishings = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("policyTermId")
    public String getPolicyTermId ( ) { 
        return this.policyTermId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("policyTermId")
    public void setPolicyTermId (String value) { 
        this.policyTermId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreSubDomainName")
    public String getInsuranceCentreSubDomainName ( ) { 
        return this.insuranceCentreSubDomainName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreSubDomainName")
    public void setInsuranceCentreSubDomainName (String value) { 
        this.insuranceCentreSubDomainName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreId")
    public String getInsuranceCentreId ( ) { 
        return this.insuranceCentreId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreId")
    public void setInsuranceCentreId (String value) { 
        this.insuranceCentreId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyId")
    public String getInsuranceCompanyId ( ) { 
        return this.insuranceCompanyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyId")
    public void setInsuranceCompanyId (String value) { 
        this.insuranceCompanyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("giftCode")
    public String getGiftCode ( ) { 
        return this.giftCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("giftCode")
    public void setGiftCode (String value) { 
        this.giftCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customerUserId")
    public String getCustomerUserId ( ) { 
        return this.customerUserId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customerUserId")
    public void setCustomerUserId (String value) { 
        this.customerUserId = value;
    }
 
}
