/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class FireInsurancePolicyFilterBuilder {
    //the instance to build
    private FireInsurancePolicyFilter fireInsurancePolicyFilter;

    /**
     * Default constructor to initialize the instance
     */
    public FireInsurancePolicyFilterBuilder() {
        fireInsurancePolicyFilter = new FireInsurancePolicyFilter();
    }

    public FireInsurancePolicyFilterBuilder insurancePolicyType(String insurancePolicyType) {
        fireInsurancePolicyFilter.setInsurancePolicyType(insurancePolicyType);
        return this;
    }

    public FireInsurancePolicyFilterBuilder insuranceExtraCoverageIds(String insuranceExtraCoverageIds) {
        fireInsurancePolicyFilter.setInsuranceExtraCoverageIds(insuranceExtraCoverageIds);
        return this;
    }

    public FireInsurancePolicyFilterBuilder valuePerSquareMeterCoverageRateId(String valuePerSquareMeterCoverageRateId) {
        fireInsurancePolicyFilter.setValuePerSquareMeterCoverageRateId(valuePerSquareMeterCoverageRateId);
        return this;
    }

    public FireInsurancePolicyFilterBuilder valueOfAppliancesFurnishing(String valueOfAppliancesFurnishing) {
        fireInsurancePolicyFilter.setValueOfAppliancesFurnishing(valueOfAppliancesFurnishing);
        return this;
    }

    public FireInsurancePolicyFilterBuilder cityId(String cityId) {
        fireInsurancePolicyFilter.setCityId(cityId);
        return this;
    }

    public FireInsurancePolicyFilterBuilder skeletonTypeId(String skeletonTypeId) {
        fireInsurancePolicyFilter.setSkeletonTypeId(skeletonTypeId);
        return this;
    }

    public FireInsurancePolicyFilterBuilder buildingTypeId(int buildingTypeId) {
        fireInsurancePolicyFilter.setBuildingTypeId(buildingTypeId);
        return this;
    }

    public FireInsurancePolicyFilterBuilder buildingArea(String buildingArea) {
        fireInsurancePolicyFilter.setBuildingArea(buildingArea);
        return this;
    }

    public FireInsurancePolicyFilterBuilder onlyAppliancesFurnishings(String onlyAppliancesFurnishings) {
        fireInsurancePolicyFilter.setOnlyAppliancesFurnishings(onlyAppliancesFurnishings);
        return this;
    }

    public FireInsurancePolicyFilterBuilder policyTermId(String policyTermId) {
        fireInsurancePolicyFilter.setPolicyTermId(policyTermId);
        return this;
    }

    public FireInsurancePolicyFilterBuilder insuranceCentreSubDomainName(String insuranceCentreSubDomainName) {
        fireInsurancePolicyFilter.setInsuranceCentreSubDomainName(insuranceCentreSubDomainName);
        return this;
    }

    public FireInsurancePolicyFilterBuilder insuranceCentreId(String insuranceCentreId) {
        fireInsurancePolicyFilter.setInsuranceCentreId(insuranceCentreId);
        return this;
    }

    public FireInsurancePolicyFilterBuilder insuranceCompanyId(String insuranceCompanyId) {
        fireInsurancePolicyFilter.setInsuranceCompanyId(insuranceCompanyId);
        return this;
    }

    public FireInsurancePolicyFilterBuilder giftCode(String giftCode) {
        fireInsurancePolicyFilter.setGiftCode(giftCode);
        return this;
    }

    public FireInsurancePolicyFilterBuilder customerUserId(String customerUserId) {
        fireInsurancePolicyFilter.setCustomerUserId(customerUserId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public FireInsurancePolicyFilter build() {
        return fireInsurancePolicyFilter;
    }
}