/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class FranchiseeBuilder {
    //the instance to build
    private Franchisee franchisee;

    /**
     * Default constructor to initialize the instance
     */
    public FranchiseeBuilder() {
        franchisee = new Franchisee();
    }

    public FranchiseeBuilder id(int id) {
        franchisee.setId(id);
        return this;
    }

    public FranchiseeBuilder title(String title) {
        franchisee.setTitle(title);
        return this;
    }

    public FranchiseeBuilder extraData(String extraData) {
        franchisee.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Franchisee build() {
        return franchisee;
    }
}