/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class GalleryDetailBuilder {
    //the instance to build
    private GalleryDetail galleryDetail;

    /**
     * Default constructor to initialize the instance
     */
    public GalleryDetailBuilder() {
        galleryDetail = new GalleryDetail();
    }

    public GalleryDetailBuilder galleryId(int galleryId) {
        galleryDetail.setGalleryId(galleryId);
        return this;
    }

    public GalleryDetailBuilder metaMediaFileId(int metaMediaFileId) {
        galleryDetail.setMetaMediaFileId(metaMediaFileId);
        return this;
    }

    public GalleryDetailBuilder metaMediaFileUrl(String metaMediaFileUrl) {
        galleryDetail.setMetaMediaFileUrl(metaMediaFileUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GalleryDetail build() {
        return galleryDetail;
    }
}