/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class GetAccessTokenUserInfoBuilder {
    //the instance to build
    private GetAccessTokenUserInfo getAccessTokenUserInfo;

    /**
     * Default constructor to initialize the instance
     */
    public GetAccessTokenUserInfoBuilder() {
        getAccessTokenUserInfo = new GetAccessTokenUserInfo();
    }

    public GetAccessTokenUserInfoBuilder id(String id) {
        getAccessTokenUserInfo.setId(id);
        return this;
    }

    public GetAccessTokenUserInfoBuilder accessToken(String accessToken) {
        getAccessTokenUserInfo.setAccessToken(accessToken);
        return this;
    }

    public GetAccessTokenUserInfoBuilder expiresIn(String expiresIn) {
        getAccessTokenUserInfo.setExpiresIn(expiresIn);
        return this;
    }

    public GetAccessTokenUserInfoBuilder refreshToken(String refreshToken) {
        getAccessTokenUserInfo.setRefreshToken(refreshToken);
        return this;
    }

    public GetAccessTokenUserInfoBuilder error(String error) {
        getAccessTokenUserInfo.setMError(error);
        return this;
    }

    public GetAccessTokenUserInfoBuilder userName(String userName) {
        getAccessTokenUserInfo.setUserName(userName);
        return this;
    }

    public GetAccessTokenUserInfoBuilder insuranceCentreName(String insuranceCentreName) {
        getAccessTokenUserInfo.setInsuranceCentreName(insuranceCentreName);
        return this;
    }

    public GetAccessTokenUserInfoBuilder insuranceCentreLogo(String insuranceCentreLogo) {
        getAccessTokenUserInfo.setInsuranceCentreLogo(insuranceCentreLogo);
        return this;
    }

    public GetAccessTokenUserInfoBuilder insuranceCentreFavicon(String insuranceCentreFavicon) {
        getAccessTokenUserInfo.setInsuranceCentreFavicon(insuranceCentreFavicon);
        return this;
    }

    public GetAccessTokenUserInfoBuilder licensed(boolean licensed) {
        getAccessTokenUserInfo.setLicensed(licensed);
        return this;
    }

    public GetAccessTokenUserInfoBuilder email(String email) {
        getAccessTokenUserInfo.setEmail(email);
        return this;
    }

    public GetAccessTokenUserInfoBuilder insuranceCentreType(int insuranceCentreType) {
        getAccessTokenUserInfo.setInsuranceCentreType(insuranceCentreType);
        return this;
    }

    public GetAccessTokenUserInfoBuilder avatarUrl(String avatarUrl) {
        getAccessTokenUserInfo.setAvatarUrl(avatarUrl);
        return this;
    }

    public GetAccessTokenUserInfoBuilder aliasName(String aliasName) {
        getAccessTokenUserInfo.setAliasName(aliasName);
        return this;
    }

    public GetAccessTokenUserInfoBuilder userGroup(int userGroup) {
        getAccessTokenUserInfo.setUserGroup(userGroup);
        return this;
    }

    public GetAccessTokenUserInfoBuilder userGroupTitle(String userGroupTitle) {
        getAccessTokenUserInfo.setUserGroupTitle(userGroupTitle);
        return this;
    }

    public GetAccessTokenUserInfoBuilder roleIds(List<String> roleIds) {
        getAccessTokenUserInfo.setRoleIds(roleIds);
        return this;
    }

    public GetAccessTokenUserInfoBuilder roleTitles(String roleTitles) {
        getAccessTokenUserInfo.setRoleTitles(roleTitles);
        return this;
    }

    public GetAccessTokenUserInfoBuilder unlimitedAccount(boolean unlimitedAccount) {
        getAccessTokenUserInfo.setUnlimitedAccount(unlimitedAccount);
        return this;
    }

    public GetAccessTokenUserInfoBuilder rolePermissions(String rolePermissions) {
        getAccessTokenUserInfo.setRolePermissions(rolePermissions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetAccessTokenUserInfo build() {
        return getAccessTokenUserInfo;
    }
}