/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class ImageAlbumBuilder {
    //the instance to build
    private ImageAlbum imageAlbum;

    /**
     * Default constructor to initialize the instance
     */
    public ImageAlbumBuilder() {
        imageAlbum = new ImageAlbum();
    }

    public ImageAlbumBuilder id(int id) {
        imageAlbum.setId(id);
        return this;
    }

    public ImageAlbumBuilder galleryType(int galleryType) {
        imageAlbum.setGalleryType(galleryType);
        return this;
    }

    public ImageAlbumBuilder title(String title) {
        imageAlbum.setTitle(title);
        return this;
    }

    public ImageAlbumBuilder alt(String alt) {
        imageAlbum.setAlt(alt);
        return this;
    }

    public ImageAlbumBuilder description(String description) {
        imageAlbum.setDescription(description);
        return this;
    }

    public ImageAlbumBuilder isActive(boolean isActive) {
        imageAlbum.setIsActive(isActive);
        return this;
    }

    public ImageAlbumBuilder isMain(boolean isMain) {
        imageAlbum.setIsMain(isMain);
        return this;
    }

    public ImageAlbumBuilder isAttachFile(boolean isAttachFile) {
        imageAlbum.setIsAttachFile(isAttachFile);
        return this;
    }

    public ImageAlbumBuilder sortPriority(String sortPriority) {
        imageAlbum.setSortPriority(sortPriority);
        return this;
    }

    public ImageAlbumBuilder createOnPersianDate(String createOnPersianDate) {
        imageAlbum.setCreateOnPersianDate(createOnPersianDate);
        return this;
    }

    public ImageAlbumBuilder metaMediaFileId(int metaMediaFileId) {
        imageAlbum.setMetaMediaFileId(metaMediaFileId);
        return this;
    }

    public ImageAlbumBuilder metaMediaFileUrl(String metaMediaFileUrl) {
        imageAlbum.setMetaMediaFileUrl(metaMediaFileUrl);
        return this;
    }

    public ImageAlbumBuilder metaMediaFileThumbnailUrl(String metaMediaFileThumbnailUrl) {
        imageAlbum.setMetaMediaFileThumbnailUrl(metaMediaFileThumbnailUrl);
        return this;
    }

    public ImageAlbumBuilder popupImageGalleryies(List<PopupImageGalleryie> popupImageGalleryies) {
        imageAlbum.setPopupImageGalleryies(popupImageGalleryies);
        return this;
    }

    public ImageAlbumBuilder galleryDetails(List<GalleryDetail> galleryDetails) {
        imageAlbum.setGalleryDetails(galleryDetails);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ImageAlbum build() {
        return imageAlbum;
    }
}