/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsuranceDataTravelInsuranceBuilder {
    //the instance to build
    private InsuranceDataTravelInsurance insuranceDataTravelInsurance;

    /**
     * Default constructor to initialize the instance
     */
    public InsuranceDataTravelInsuranceBuilder() {
        insuranceDataTravelInsurance = new InsuranceDataTravelInsurance();
    }

    public InsuranceDataTravelInsuranceBuilder travelInsurancePolicyExtendView(TravelInsurancePolicyExtendView travelInsurancePolicyExtendView) {
        insuranceDataTravelInsurance.setTravelInsurancePolicyExtendView(travelInsurancePolicyExtendView);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder travelInsurancePolicyFilter(TravelInsurancePolicyFilter travelInsurancePolicyFilter) {
        insuranceDataTravelInsurance.setTravelInsurancePolicyFilter(travelInsurancePolicyFilter);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder id(int id) {
        insuranceDataTravelInsurance.setId(id);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder selectedInsurancePolicyHasBeenChanged(boolean selectedInsurancePolicyHasBeenChanged) {
        insuranceDataTravelInsurance.setSelectedInsurancePolicyHasBeenChanged(selectedInsurancePolicyHasBeenChanged);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder isPaymented(boolean isPaymented) {
        insuranceDataTravelInsurance.setIsPaymented(isPaymented);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder payable(String payable) {
        insuranceDataTravelInsurance.setPayable(payable);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder paymented(String paymented) {
        insuranceDataTravelInsurance.setPaymented(paymented);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder conflict(String conflict) {
        insuranceDataTravelInsurance.setConflict(conflict);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder hasConflictDocument(boolean hasConflictDocument) {
        insuranceDataTravelInsurance.setHasConflictDocument(hasConflictDocument);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder initialPrice(String initialPrice) {
        insuranceDataTravelInsurance.setInitialPrice(initialPrice);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder finalPrice(String finalPrice) {
        insuranceDataTravelInsurance.setFinalPrice(finalPrice);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder insuranceCompanyName(String insuranceCompanyName) {
        insuranceDataTravelInsurance.setInsuranceCompanyName(insuranceCompanyName);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder insuranceCentreName(String insuranceCentreName) {
        insuranceDataTravelInsurance.setInsuranceCentreName(insuranceCentreName);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder isInsuranceCentreAdmin(boolean isInsuranceCentreAdmin) {
        insuranceDataTravelInsurance.setIsInsuranceCentreAdmin(isInsuranceCentreAdmin);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder insurancePolicyPaymentDocuments(List<String> insurancePolicyPaymentDocuments) {
        insuranceDataTravelInsurance.setInsurancePolicyPaymentDocuments(insurancePolicyPaymentDocuments);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder insurancePolicyConflict(String insurancePolicyConflict) {
        insuranceDataTravelInsurance.setInsurancePolicyConflict(insurancePolicyConflict);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder insurancePolicyCondition(String insurancePolicyCondition) {
        insuranceDataTravelInsurance.setInsurancePolicyCondition(insurancePolicyCondition);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder person(String person) {
        insuranceDataTravelInsurance.setPerson(person);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder insurancePolicy(String insurancePolicy) {
        insuranceDataTravelInsurance.setInsurancePolicy(insurancePolicy);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder shoppingCard(String shoppingCard) {
        insuranceDataTravelInsurance.setShoppingCard(shoppingCard);
        return this;
    }

    public InsuranceDataTravelInsuranceBuilder shoppingCardPostalPacket(String shoppingCardPostalPacket) {
        insuranceDataTravelInsurance.setShoppingCardPostalPacket(shoppingCardPostalPacket);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsuranceDataTravelInsurance build() {
        return insuranceDataTravelInsurance;
    }
}