/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsurancePolicyConditionBuilder {
    //the instance to build
    private InsurancePolicyCondition insurancePolicyCondition;

    /**
     * Default constructor to initialize the instance
     */
    public InsurancePolicyConditionBuilder() {
        insurancePolicyCondition = new InsurancePolicyCondition();
    }

    public InsurancePolicyConditionBuilder id(int id) {
        insurancePolicyCondition.setId(id);
        return this;
    }

    /**
     * شناسه ی مرکز بیمه
     */
    public InsurancePolicyConditionBuilder insuranceCentreId(int insuranceCentreId) {
        insurancePolicyCondition.setInsuranceCentreId(insuranceCentreId);
        return this;
    }

    /**
     * شناسه ی نوع بیمه نامه ی شرکت بیمه
     */
    public InsurancePolicyConditionBuilder insuranceCompanyPolicyTypeId(int insuranceCompanyPolicyTypeId) {
        insurancePolicyCondition.setInsuranceCompanyPolicyTypeId(insuranceCompanyPolicyTypeId);
        return this;
    }

    /**
     * الویت نمایش
     */
    public InsurancePolicyConditionBuilder displayPriority(String displayPriority) {
        insurancePolicyCondition.setDisplayPriority(displayPriority);
        return this;
    }

    /**
     * امکان صدور بیمه نامه
     */
    public InsurancePolicyConditionBuilder issueInsurance(String issueInsurance) {
        insurancePolicyCondition.setIssueInsurance(issueInsurance);
        return this;
    }

    /**
     * ارزیابی خسارت
     */
    public InsurancePolicyConditionBuilder damageAssessment(String damageAssessment) {
        insurancePolicyCondition.setDamageAssessment(damageAssessment);
        return this;
    }

    /**
     * پرداخت نقدی
     */
    public InsurancePolicyConditionBuilder cashPayment(String cashPayment) {
        insurancePolicyCondition.setCashPayment(cashPayment);
        return this;
    }

    /**
     * پرداخت اقساطی
     */
    public InsurancePolicyConditionBuilder installmentsPayment(String installmentsPayment) {
        insurancePolicyCondition.setInstallmentsPayment(installmentsPayment);
        return this;
    }

    /**
     * درصدر پیش پرداخت
     */
    public InsurancePolicyConditionBuilder prepaymentPercent(String prepaymentPercent) {
        insurancePolicyCondition.setPrepaymentPercent(prepaymentPercent);
        return this;
    }

    /**
     * تعداد اقساط از
     */
    public InsurancePolicyConditionBuilder countInstallmentFrom(String countInstallmentFrom) {
        insurancePolicyCondition.setCountInstallmentFrom(countInstallmentFrom);
        return this;
    }

    /**
     * تعداد اقساط تا
     */
    public InsurancePolicyConditionBuilder countInstallmentTo(String countInstallmentTo) {
        insurancePolicyCondition.setCountInstallmentTo(countInstallmentTo);
        return this;
    }

    /**
     * روش فروش
     */
    public InsurancePolicyConditionBuilder paymentMethods(String paymentMethods) {
        insurancePolicyCondition.setPaymentMethods(paymentMethods);
        return this;
    }

    /**
     * پروموشن
     */
    public InsurancePolicyConditionBuilder promotion(String promotion) {
        insurancePolicyCondition.setPromotion(promotion);
        return this;
    }

    /**
     * وضعیت فعال
     */
    public InsurancePolicyConditionBuilder isActive(boolean isActive) {
        insurancePolicyCondition.setIsActive(isActive);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsurancePolicyCondition build() {
        return insurancePolicyCondition;
    }
}