/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class InsurancePolicyCondition 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4611234572291564485L;
    private int id;
    private int insuranceCentreId;
    private int insuranceCompanyPolicyTypeId;
    private String displayPriority;
    private String issueInsurance;
    private String damageAssessment;
    private String cashPayment;
    private String installmentsPayment;
    private String prepaymentPercent;
    private String countInstallmentFrom;
    private String countInstallmentTo;
    private String paymentMethods;
    private String promotion;
    private boolean isActive;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
    }
 
    /** GETTER
     * شناسه ی مرکز بیمه
     */
    @JsonGetter("insuranceCentreId")
    public int getInsuranceCentreId ( ) { 
        return this.insuranceCentreId;
    }
    
    /** SETTER
     * شناسه ی مرکز بیمه
     */
    @JsonSetter("insuranceCentreId")
    public void setInsuranceCentreId (int value) { 
        this.insuranceCentreId = value;
    }
 
    /** GETTER
     * شناسه ی نوع بیمه نامه ی شرکت بیمه
     */
    @JsonGetter("insuranceCompanyPolicyTypeId")
    public int getInsuranceCompanyPolicyTypeId ( ) { 
        return this.insuranceCompanyPolicyTypeId;
    }
    
    /** SETTER
     * شناسه ی نوع بیمه نامه ی شرکت بیمه
     */
    @JsonSetter("insuranceCompanyPolicyTypeId")
    public void setInsuranceCompanyPolicyTypeId (int value) { 
        this.insuranceCompanyPolicyTypeId = value;
    }
 
    /** GETTER
     * الویت نمایش
     */
    @JsonGetter("displayPriority")
    public String getDisplayPriority ( ) { 
        return this.displayPriority;
    }
    
    /** SETTER
     * الویت نمایش
     */
    @JsonSetter("displayPriority")
    public void setDisplayPriority (String value) { 
        this.displayPriority = value;
    }
 
    /** GETTER
     * امکان صدور بیمه نامه
     */
    @JsonGetter("issueInsurance")
    public String getIssueInsurance ( ) { 
        return this.issueInsurance;
    }
    
    /** SETTER
     * امکان صدور بیمه نامه
     */
    @JsonSetter("issueInsurance")
    public void setIssueInsurance (String value) { 
        this.issueInsurance = value;
    }
 
    /** GETTER
     * ارزیابی خسارت
     */
    @JsonGetter("damageAssessment")
    public String getDamageAssessment ( ) { 
        return this.damageAssessment;
    }
    
    /** SETTER
     * ارزیابی خسارت
     */
    @JsonSetter("damageAssessment")
    public void setDamageAssessment (String value) { 
        this.damageAssessment = value;
    }
 
    /** GETTER
     * پرداخت نقدی
     */
    @JsonGetter("cashPayment")
    public String getCashPayment ( ) { 
        return this.cashPayment;
    }
    
    /** SETTER
     * پرداخت نقدی
     */
    @JsonSetter("cashPayment")
    public void setCashPayment (String value) { 
        this.cashPayment = value;
    }
 
    /** GETTER
     * پرداخت اقساطی
     */
    @JsonGetter("installmentsPayment")
    public String getInstallmentsPayment ( ) { 
        return this.installmentsPayment;
    }
    
    /** SETTER
     * پرداخت اقساطی
     */
    @JsonSetter("installmentsPayment")
    public void setInstallmentsPayment (String value) { 
        this.installmentsPayment = value;
    }
 
    /** GETTER
     * درصدر پیش پرداخت
     */
    @JsonGetter("prepaymentPercent")
    public String getPrepaymentPercent ( ) { 
        return this.prepaymentPercent;
    }
    
    /** SETTER
     * درصدر پیش پرداخت
     */
    @JsonSetter("prepaymentPercent")
    public void setPrepaymentPercent (String value) { 
        this.prepaymentPercent = value;
    }
 
    /** GETTER
     * تعداد اقساط از
     */
    @JsonGetter("countInstallmentFrom")
    public String getCountInstallmentFrom ( ) { 
        return this.countInstallmentFrom;
    }
    
    /** SETTER
     * تعداد اقساط از
     */
    @JsonSetter("countInstallmentFrom")
    public void setCountInstallmentFrom (String value) { 
        this.countInstallmentFrom = value;
    }
 
    /** GETTER
     * تعداد اقساط تا
     */
    @JsonGetter("countInstallmentTo")
    public String getCountInstallmentTo ( ) { 
        return this.countInstallmentTo;
    }
    
    /** SETTER
     * تعداد اقساط تا
     */
    @JsonSetter("countInstallmentTo")
    public void setCountInstallmentTo (String value) { 
        this.countInstallmentTo = value;
    }
 
    /** GETTER
     * روش فروش
     */
    @JsonGetter("paymentMethods")
    public String getPaymentMethods ( ) { 
        return this.paymentMethods;
    }
    
    /** SETTER
     * روش فروش
     */
    @JsonSetter("paymentMethods")
    public void setPaymentMethods (String value) { 
        this.paymentMethods = value;
    }
 
    /** GETTER
     * پروموشن
     */
    @JsonGetter("promotion")
    public String getPromotion ( ) { 
        return this.promotion;
    }
    
    /** SETTER
     * پروموشن
     */
    @JsonSetter("promotion")
    public void setPromotion (String value) { 
        this.promotion = value;
    }
 
    /** GETTER
     * وضعیت فعال
     */
    @JsonGetter("isActive")
    public boolean getIsActive ( ) { 
        return this.isActive;
    }
    
    /** SETTER
     * وضعیت فعال
     */
    @JsonSetter("isActive")
    public void setIsActive (boolean value) { 
        this.isActive = value;
    }
 
}
