/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsuranceDataElevatorInsuranceBuilder {
    //the instance to build
    private InsuranceDataElevatorInsurance insuranceDataElevatorInsurance;

    /**
     * Default constructor to initialize the instance
     */
    public InsuranceDataElevatorInsuranceBuilder() {
        insuranceDataElevatorInsurance = new InsuranceDataElevatorInsurance();
    }

    public InsuranceDataElevatorInsuranceBuilder elevatorInsurancePolicyExtendView(ElevatorInsurancePolicyExtendView elevatorInsurancePolicyExtendView) {
        insuranceDataElevatorInsurance.setElevatorInsurancePolicyExtendView(elevatorInsurancePolicyExtendView);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder elevatorInsurancePolicyFilter(ElevatorInsurancePolicyFilter elevatorInsurancePolicyFilter) {
        insuranceDataElevatorInsurance.setElevatorInsurancePolicyFilter(elevatorInsurancePolicyFilter);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder id(int id) {
        insuranceDataElevatorInsurance.setId(id);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder selectedInsurancePolicyHasBeenChanged(boolean selectedInsurancePolicyHasBeenChanged) {
        insuranceDataElevatorInsurance.setSelectedInsurancePolicyHasBeenChanged(selectedInsurancePolicyHasBeenChanged);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder isPaymented(boolean isPaymented) {
        insuranceDataElevatorInsurance.setIsPaymented(isPaymented);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder payable(String payable) {
        insuranceDataElevatorInsurance.setPayable(payable);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder paymented(String paymented) {
        insuranceDataElevatorInsurance.setPaymented(paymented);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder conflict(String conflict) {
        insuranceDataElevatorInsurance.setConflict(conflict);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder hasConflictDocument(boolean hasConflictDocument) {
        insuranceDataElevatorInsurance.setHasConflictDocument(hasConflictDocument);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder initialPrice(String initialPrice) {
        insuranceDataElevatorInsurance.setInitialPrice(initialPrice);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder finalPrice(String finalPrice) {
        insuranceDataElevatorInsurance.setFinalPrice(finalPrice);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder insuranceCompanyName(String insuranceCompanyName) {
        insuranceDataElevatorInsurance.setInsuranceCompanyName(insuranceCompanyName);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder insuranceCentreName(String insuranceCentreName) {
        insuranceDataElevatorInsurance.setInsuranceCentreName(insuranceCentreName);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder isInsuranceCentreAdmin(boolean isInsuranceCentreAdmin) {
        insuranceDataElevatorInsurance.setIsInsuranceCentreAdmin(isInsuranceCentreAdmin);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder insurancePolicyPaymentDocuments(List<String> insurancePolicyPaymentDocuments) {
        insuranceDataElevatorInsurance.setInsurancePolicyPaymentDocuments(insurancePolicyPaymentDocuments);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder insurancePolicyConflict(String insurancePolicyConflict) {
        insuranceDataElevatorInsurance.setInsurancePolicyConflict(insurancePolicyConflict);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder insurancePolicyCondition(String insurancePolicyCondition) {
        insuranceDataElevatorInsurance.setInsurancePolicyCondition(insurancePolicyCondition);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder person(String person) {
        insuranceDataElevatorInsurance.setPerson(person);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder insurancePolicy(String insurancePolicy) {
        insuranceDataElevatorInsurance.setInsurancePolicy(insurancePolicy);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder shoppingCard(String shoppingCard) {
        insuranceDataElevatorInsurance.setShoppingCard(shoppingCard);
        return this;
    }

    public InsuranceDataElevatorInsuranceBuilder shoppingCardPostalPacket(String shoppingCardPostalPacket) {
        insuranceDataElevatorInsurance.setShoppingCardPostalPacket(shoppingCardPostalPacket);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsuranceDataElevatorInsurance build() {
        return insuranceDataElevatorInsurance;
    }
}