/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsuranceDataBuilder {
    //the instance to build
    private InsuranceData insuranceData;

    /**
     * Default constructor to initialize the instance
     */
    public InsuranceDataBuilder() {
        insuranceData = new InsuranceData();
    }

    public InsuranceDataBuilder electronicEquipmentInsurancePolicyExtendView(ElectronicEquipmentInsurancePolicyExtendView electronicEquipmentInsurancePolicyExtendView) {
        insuranceData.setElectronicEquipmentInsurancePolicyExtendView(electronicEquipmentInsurancePolicyExtendView);
        return this;
    }

    public InsuranceDataBuilder electronicEquipmentInsurancePolicyFilter(ElectronicEquipmentInsurancePolicyFilter electronicEquipmentInsurancePolicyFilter) {
        insuranceData.setElectronicEquipmentInsurancePolicyFilter(electronicEquipmentInsurancePolicyFilter);
        return this;
    }

    public InsuranceDataBuilder id(int id) {
        insuranceData.setId(id);
        return this;
    }

    public InsuranceDataBuilder selectedInsurancePolicyHasBeenChanged(boolean selectedInsurancePolicyHasBeenChanged) {
        insuranceData.setSelectedInsurancePolicyHasBeenChanged(selectedInsurancePolicyHasBeenChanged);
        return this;
    }

    public InsuranceDataBuilder isPaymented(boolean isPaymented) {
        insuranceData.setIsPaymented(isPaymented);
        return this;
    }

    public InsuranceDataBuilder payable(String payable) {
        insuranceData.setPayable(payable);
        return this;
    }

    public InsuranceDataBuilder paymented(String paymented) {
        insuranceData.setPaymented(paymented);
        return this;
    }

    public InsuranceDataBuilder conflict(String conflict) {
        insuranceData.setConflict(conflict);
        return this;
    }

    public InsuranceDataBuilder hasConflictDocument(boolean hasConflictDocument) {
        insuranceData.setHasConflictDocument(hasConflictDocument);
        return this;
    }

    public InsuranceDataBuilder initialPrice(String initialPrice) {
        insuranceData.setInitialPrice(initialPrice);
        return this;
    }

    public InsuranceDataBuilder finalPrice(String finalPrice) {
        insuranceData.setFinalPrice(finalPrice);
        return this;
    }

    public InsuranceDataBuilder insuranceCompanyName(String insuranceCompanyName) {
        insuranceData.setInsuranceCompanyName(insuranceCompanyName);
        return this;
    }

    public InsuranceDataBuilder insuranceCentreName(String insuranceCentreName) {
        insuranceData.setInsuranceCentreName(insuranceCentreName);
        return this;
    }

    public InsuranceDataBuilder isInsuranceCentreAdmin(boolean isInsuranceCentreAdmin) {
        insuranceData.setIsInsuranceCentreAdmin(isInsuranceCentreAdmin);
        return this;
    }

    public InsuranceDataBuilder insurancePolicyPaymentDocuments(List<String> insurancePolicyPaymentDocuments) {
        insuranceData.setInsurancePolicyPaymentDocuments(insurancePolicyPaymentDocuments);
        return this;
    }

    public InsuranceDataBuilder insurancePolicyConflict(String insurancePolicyConflict) {
        insuranceData.setInsurancePolicyConflict(insurancePolicyConflict);
        return this;
    }

    public InsuranceDataBuilder insurancePolicyCondition(String insurancePolicyCondition) {
        insuranceData.setInsurancePolicyCondition(insurancePolicyCondition);
        return this;
    }

    public InsuranceDataBuilder person(String person) {
        insuranceData.setPerson(person);
        return this;
    }

    public InsuranceDataBuilder insurancePolicy(String insurancePolicy) {
        insuranceData.setInsurancePolicy(insurancePolicy);
        return this;
    }

    public InsuranceDataBuilder shoppingCard(String shoppingCard) {
        insuranceData.setShoppingCard(shoppingCard);
        return this;
    }

    public InsuranceDataBuilder shoppingCardPostalPacket(String shoppingCardPostalPacket) {
        insuranceData.setShoppingCardPostalPacket(shoppingCardPostalPacket);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsuranceData build() {
        return insuranceData;
    }
}