/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class InsuranceDataLiabilityDoctorInsurance 
        implements java.io.Serializable {
    private static final long serialVersionUID = -702938000115276026L;
    private LiabilityDoctorInsurancePolicyExtendView liabilityDoctorInsurancePolicyExtendView;
    private LiabilityDoctorInsurancePolicyFilter liabilityDoctorInsurancePolicyFilter;
    private int id;
    private boolean selectedInsurancePolicyHasBeenChanged;
    private boolean isPaymented;
    private String payable;
    private String paymented;
    private String conflict;
    private boolean hasConflictDocument;
    private String initialPrice;
    private String finalPrice;
    private String insuranceCompanyName;
    private String insuranceCentreName;
    private boolean isInsuranceCentreAdmin;
    private List<String> insurancePolicyPaymentDocuments;
    private String insurancePolicyConflict;
    private String insurancePolicyCondition;
    private String person;
    private String insurancePolicy;
    private String shoppingCard;
    private String shoppingCardPostalPacket;
    /** GETTER
     * شرایط اضافه ی بیمه نامه
     */
    @JsonGetter("liabilityDoctorInsurancePolicyExtendView")
    public LiabilityDoctorInsurancePolicyExtendView getLiabilityDoctorInsurancePolicyExtendView ( ) { 
        return this.liabilityDoctorInsurancePolicyExtendView;
    }
    
    /** SETTER
     * شرایط اضافه ی بیمه نامه
     */
    @JsonSetter("liabilityDoctorInsurancePolicyExtendView")
    public void setLiabilityDoctorInsurancePolicyExtendView (LiabilityDoctorInsurancePolicyExtendView value) { 
        this.liabilityDoctorInsurancePolicyExtendView = value;
    }
 
    /** GETTER
     * فیلتر های بیمه نامه
     */
    @JsonGetter("liabilityDoctorInsurancePolicyFilter")
    public LiabilityDoctorInsurancePolicyFilter getLiabilityDoctorInsurancePolicyFilter ( ) { 
        return this.liabilityDoctorInsurancePolicyFilter;
    }
    
    /** SETTER
     * فیلتر های بیمه نامه
     */
    @JsonSetter("liabilityDoctorInsurancePolicyFilter")
    public void setLiabilityDoctorInsurancePolicyFilter (LiabilityDoctorInsurancePolicyFilter value) { 
        this.liabilityDoctorInsurancePolicyFilter = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
    }
 
    /** GETTER
     * بیمه نامه تغییر کرده؟
     */
    @JsonGetter("selectedInsurancePolicyHasBeenChanged")
    public boolean getSelectedInsurancePolicyHasBeenChanged ( ) { 
        return this.selectedInsurancePolicyHasBeenChanged;
    }
    
    /** SETTER
     * بیمه نامه تغییر کرده؟
     */
    @JsonSetter("selectedInsurancePolicyHasBeenChanged")
    public void setSelectedInsurancePolicyHasBeenChanged (boolean value) { 
        this.selectedInsurancePolicyHasBeenChanged = value;
    }
 
    /** GETTER
     * پرداخت شده؟
     */
    @JsonGetter("isPaymented")
    public boolean getIsPaymented ( ) { 
        return this.isPaymented;
    }
    
    /** SETTER
     * پرداخت شده؟
     */
    @JsonSetter("isPaymented")
    public void setIsPaymented (boolean value) { 
        this.isPaymented = value;
    }
 
    /** GETTER
     * قابل پرداخت؟
     */
    @JsonGetter("payable")
    public String getPayable ( ) { 
        return this.payable;
    }
    
    /** SETTER
     * قابل پرداخت؟
     */
    @JsonSetter("payable")
    public void setPayable (String value) { 
        this.payable = value;
    }
 
    /** GETTER
     * پرداخت شده؟
     */
    @JsonGetter("paymented")
    public String getPaymented ( ) { 
        return this.paymented;
    }
    
    /** SETTER
     * پرداخت شده؟
     */
    @JsonSetter("paymented")
    public void setPaymented (String value) { 
        this.paymented = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("conflict")
    public String getConflict ( ) { 
        return this.conflict;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("conflict")
    public void setConflict (String value) { 
        this.conflict = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasConflictDocument")
    public boolean getHasConflictDocument ( ) { 
        return this.hasConflictDocument;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasConflictDocument")
    public void setHasConflictDocument (boolean value) { 
        this.hasConflictDocument = value;
    }
 
    /** GETTER
     * قیمت پایه
     */
    @JsonGetter("initialPrice")
    public String getInitialPrice ( ) { 
        return this.initialPrice;
    }
    
    /** SETTER
     * قیمت پایه
     */
    @JsonSetter("initialPrice")
    public void setInitialPrice (String value) { 
        this.initialPrice = value;
    }
 
    /** GETTER
     * قیمت نهایی
     */
    @JsonGetter("finalPrice")
    public String getFinalPrice ( ) { 
        return this.finalPrice;
    }
    
    /** SETTER
     * قیمت نهایی
     */
    @JsonSetter("finalPrice")
    public void setFinalPrice (String value) { 
        this.finalPrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyName")
    public String getInsuranceCompanyName ( ) { 
        return this.insuranceCompanyName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyName")
    public void setInsuranceCompanyName (String value) { 
        this.insuranceCompanyName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreName")
    public String getInsuranceCentreName ( ) { 
        return this.insuranceCentreName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreName")
    public void setInsuranceCentreName (String value) { 
        this.insuranceCentreName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isInsuranceCentreAdmin")
    public boolean getIsInsuranceCentreAdmin ( ) { 
        return this.isInsuranceCentreAdmin;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isInsuranceCentreAdmin")
    public void setIsInsuranceCentreAdmin (boolean value) { 
        this.isInsuranceCentreAdmin = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyPaymentDocuments")
    public List<String> getInsurancePolicyPaymentDocuments ( ) { 
        return this.insurancePolicyPaymentDocuments;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyPaymentDocuments")
    public void setInsurancePolicyPaymentDocuments (List<String> value) { 
        this.insurancePolicyPaymentDocuments = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyConflict")
    public String getInsurancePolicyConflict ( ) { 
        return this.insurancePolicyConflict;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyConflict")
    public void setInsurancePolicyConflict (String value) { 
        this.insurancePolicyConflict = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyCondition")
    public String getInsurancePolicyCondition ( ) { 
        return this.insurancePolicyCondition;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyCondition")
    public void setInsurancePolicyCondition (String value) { 
        this.insurancePolicyCondition = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("person")
    public String getPerson ( ) { 
        return this.person;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("person")
    public void setPerson (String value) { 
        this.person = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicy")
    public String getInsurancePolicy ( ) { 
        return this.insurancePolicy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicy")
    public void setInsurancePolicy (String value) { 
        this.insurancePolicy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shoppingCard")
    public String getShoppingCard ( ) { 
        return this.shoppingCard;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shoppingCard")
    public void setShoppingCard (String value) { 
        this.shoppingCard = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("shoppingCardPostalPacket")
    public String getShoppingCardPostalPacket ( ) { 
        return this.shoppingCardPostalPacket;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("shoppingCardPostalPacket")
    public void setShoppingCardPostalPacket (String value) { 
        this.shoppingCardPostalPacket = value;
    }
 
}
