/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsurancePolicyTermBuilder {
    //the instance to build
    private InsurancePolicyTerm insurancePolicyTerm;

    /**
     * Default constructor to initialize the instance
     */
    public InsurancePolicyTermBuilder() {
        insurancePolicyTerm = new InsurancePolicyTerm();
    }

    public InsurancePolicyTermBuilder id(int id) {
        insurancePolicyTerm.setId(id);
        return this;
    }

    public InsurancePolicyTermBuilder title(String title) {
        insurancePolicyTerm.setTitle(title);
        return this;
    }

    public InsurancePolicyTermBuilder extraData(String extraData) {
        insurancePolicyTerm.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsurancePolicyTerm build() {
        return insurancePolicyTerm;
    }
}