/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class InsuranceCentrePortal 
        implements java.io.Serializable {
    private static final long serialVersionUID = 2123984918323260382L;
    private int insuranceCentreId;
    private String centreName;
    private String subDomainName;
    private String title;
    private String subTitle;
    private String contactUs;
    private String aboutUs;
    private String ourService;
    private String termsConditions;
    private String copyright;
    private String headerTitle;
    private String headerBody;
    private String footerColor;
    private String backgroundColor;
    private boolean licensed;
    private String defaultLogo;
    private String titleColor;
    private String subTitleColor;
    private String eTrustSymbol;
    private String digitalMediaOrganizerSymbol;
    private String googlePlus;
    private String telegram;
    private String instagram;
    private String faceBook;
    private String twitter;
    private String saturdayToWednesdayFromHour;
    private String saturdayToWednesdayToHour;
    private String thursdayFromHour;
    private String thursdayToHour;
    private String fridayFromHour;
    private String fridayToHour;
    private int metaMediaFileHeaderId;
    private String metaMediaFileHeaderUrl;
    private int metaMediaFileLogoId;
    private String metaMediaFileLogoUrl;
    private int metaMediaFileFaviconId;
    private String metaMediaFileFaviconUrl;
    private String metaMediaFileFooterId;
    private String metaMediaFileFooterUrl;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreId")
    public int getInsuranceCentreId ( ) { 
        return this.insuranceCentreId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreId")
    public void setInsuranceCentreId (int value) { 
        this.insuranceCentreId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("centreName")
    public String getCentreName ( ) { 
        return this.centreName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("centreName")
    public void setCentreName (String value) { 
        this.centreName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("subDomainName")
    public String getSubDomainName ( ) { 
        return this.subDomainName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("subDomainName")
    public void setSubDomainName (String value) { 
        this.subDomainName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("subTitle")
    public String getSubTitle ( ) { 
        return this.subTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("subTitle")
    public void setSubTitle (String value) { 
        this.subTitle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("contactUs")
    public String getContactUs ( ) { 
        return this.contactUs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("contactUs")
    public void setContactUs (String value) { 
        this.contactUs = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("aboutUs")
    public String getAboutUs ( ) { 
        return this.aboutUs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("aboutUs")
    public void setAboutUs (String value) { 
        this.aboutUs = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ourService")
    public String getOurService ( ) { 
        return this.ourService;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ourService")
    public void setOurService (String value) { 
        this.ourService = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("termsConditions")
    public String getTermsConditions ( ) { 
        return this.termsConditions;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("termsConditions")
    public void setTermsConditions (String value) { 
        this.termsConditions = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("copyright")
    public String getCopyright ( ) { 
        return this.copyright;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("copyright")
    public void setCopyright (String value) { 
        this.copyright = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("headerTitle")
    public String getHeaderTitle ( ) { 
        return this.headerTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("headerTitle")
    public void setHeaderTitle (String value) { 
        this.headerTitle = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("headerBody")
    public String getHeaderBody ( ) { 
        return this.headerBody;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("headerBody")
    public void setHeaderBody (String value) { 
        this.headerBody = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("footerColor")
    public String getFooterColor ( ) { 
        return this.footerColor;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("footerColor")
    public void setFooterColor (String value) { 
        this.footerColor = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("backgroundColor")
    public String getBackgroundColor ( ) { 
        return this.backgroundColor;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("backgroundColor")
    public void setBackgroundColor (String value) { 
        this.backgroundColor = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("licensed")
    public boolean getLicensed ( ) { 
        return this.licensed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("licensed")
    public void setLicensed (boolean value) { 
        this.licensed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("defaultLogo")
    public String getDefaultLogo ( ) { 
        return this.defaultLogo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("defaultLogo")
    public void setDefaultLogo (String value) { 
        this.defaultLogo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("titleColor")
    public String getTitleColor ( ) { 
        return this.titleColor;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("titleColor")
    public void setTitleColor (String value) { 
        this.titleColor = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("subTitleColor")
    public String getSubTitleColor ( ) { 
        return this.subTitleColor;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("subTitleColor")
    public void setSubTitleColor (String value) { 
        this.subTitleColor = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("eTrustSymbol")
    public String getETrustSymbol ( ) { 
        return this.eTrustSymbol;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("eTrustSymbol")
    public void setETrustSymbol (String value) { 
        this.eTrustSymbol = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("digitalMediaOrganizerSymbol")
    public String getDigitalMediaOrganizerSymbol ( ) { 
        return this.digitalMediaOrganizerSymbol;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("digitalMediaOrganizerSymbol")
    public void setDigitalMediaOrganizerSymbol (String value) { 
        this.digitalMediaOrganizerSymbol = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("googlePlus")
    public String getGooglePlus ( ) { 
        return this.googlePlus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("googlePlus")
    public void setGooglePlus (String value) { 
        this.googlePlus = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("telegram")
    public String getTelegram ( ) { 
        return this.telegram;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("telegram")
    public void setTelegram (String value) { 
        this.telegram = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("instagram")
    public String getInstagram ( ) { 
        return this.instagram;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("instagram")
    public void setInstagram (String value) { 
        this.instagram = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("faceBook")
    public String getFaceBook ( ) { 
        return this.faceBook;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("faceBook")
    public void setFaceBook (String value) { 
        this.faceBook = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("twitter")
    public String getTwitter ( ) { 
        return this.twitter;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("twitter")
    public void setTwitter (String value) { 
        this.twitter = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("saturdayToWednesdayFromHour")
    public String getSaturdayToWednesdayFromHour ( ) { 
        return this.saturdayToWednesdayFromHour;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("saturdayToWednesdayFromHour")
    public void setSaturdayToWednesdayFromHour (String value) { 
        this.saturdayToWednesdayFromHour = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("saturdayToWednesdayToHour")
    public String getSaturdayToWednesdayToHour ( ) { 
        return this.saturdayToWednesdayToHour;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("saturdayToWednesdayToHour")
    public void setSaturdayToWednesdayToHour (String value) { 
        this.saturdayToWednesdayToHour = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("thursdayFromHour")
    public String getThursdayFromHour ( ) { 
        return this.thursdayFromHour;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("thursdayFromHour")
    public void setThursdayFromHour (String value) { 
        this.thursdayFromHour = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("thursdayToHour")
    public String getThursdayToHour ( ) { 
        return this.thursdayToHour;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("thursdayToHour")
    public void setThursdayToHour (String value) { 
        this.thursdayToHour = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fridayFromHour")
    public String getFridayFromHour ( ) { 
        return this.fridayFromHour;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fridayFromHour")
    public void setFridayFromHour (String value) { 
        this.fridayFromHour = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fridayToHour")
    public String getFridayToHour ( ) { 
        return this.fridayToHour;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fridayToHour")
    public void setFridayToHour (String value) { 
        this.fridayToHour = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileHeaderId")
    public int getMetaMediaFileHeaderId ( ) { 
        return this.metaMediaFileHeaderId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileHeaderId")
    public void setMetaMediaFileHeaderId (int value) { 
        this.metaMediaFileHeaderId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileHeaderUrl")
    public String getMetaMediaFileHeaderUrl ( ) { 
        return this.metaMediaFileHeaderUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileHeaderUrl")
    public void setMetaMediaFileHeaderUrl (String value) { 
        this.metaMediaFileHeaderUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileLogoId")
    public int getMetaMediaFileLogoId ( ) { 
        return this.metaMediaFileLogoId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileLogoId")
    public void setMetaMediaFileLogoId (int value) { 
        this.metaMediaFileLogoId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileLogoUrl")
    public String getMetaMediaFileLogoUrl ( ) { 
        return this.metaMediaFileLogoUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileLogoUrl")
    public void setMetaMediaFileLogoUrl (String value) { 
        this.metaMediaFileLogoUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileFaviconId")
    public int getMetaMediaFileFaviconId ( ) { 
        return this.metaMediaFileFaviconId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileFaviconId")
    public void setMetaMediaFileFaviconId (int value) { 
        this.metaMediaFileFaviconId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileFaviconUrl")
    public String getMetaMediaFileFaviconUrl ( ) { 
        return this.metaMediaFileFaviconUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileFaviconUrl")
    public void setMetaMediaFileFaviconUrl (String value) { 
        this.metaMediaFileFaviconUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileFooterId")
    public String getMetaMediaFileFooterId ( ) { 
        return this.metaMediaFileFooterId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileFooterId")
    public void setMetaMediaFileFooterId (String value) { 
        this.metaMediaFileFooterId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("metaMediaFileFooterUrl")
    public String getMetaMediaFileFooterUrl ( ) { 
        return this.metaMediaFileFooterUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("metaMediaFileFooterUrl")
    public void setMetaMediaFileFooterUrl (String value) { 
        this.metaMediaFileFooterUrl = value;
    }
 
}
