/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsuranceCentrePortalBuilder {
    //the instance to build
    private InsuranceCentrePortal insuranceCentrePortal;

    /**
     * Default constructor to initialize the instance
     */
    public InsuranceCentrePortalBuilder() {
        insuranceCentrePortal = new InsuranceCentrePortal();
    }

    public InsuranceCentrePortalBuilder insuranceCentreId(int insuranceCentreId) {
        insuranceCentrePortal.setInsuranceCentreId(insuranceCentreId);
        return this;
    }

    public InsuranceCentrePortalBuilder centreName(String centreName) {
        insuranceCentrePortal.setCentreName(centreName);
        return this;
    }

    public InsuranceCentrePortalBuilder subDomainName(String subDomainName) {
        insuranceCentrePortal.setSubDomainName(subDomainName);
        return this;
    }

    public InsuranceCentrePortalBuilder title(String title) {
        insuranceCentrePortal.setTitle(title);
        return this;
    }

    public InsuranceCentrePortalBuilder subTitle(String subTitle) {
        insuranceCentrePortal.setSubTitle(subTitle);
        return this;
    }

    public InsuranceCentrePortalBuilder contactUs(String contactUs) {
        insuranceCentrePortal.setContactUs(contactUs);
        return this;
    }

    public InsuranceCentrePortalBuilder aboutUs(String aboutUs) {
        insuranceCentrePortal.setAboutUs(aboutUs);
        return this;
    }

    public InsuranceCentrePortalBuilder ourService(String ourService) {
        insuranceCentrePortal.setOurService(ourService);
        return this;
    }

    public InsuranceCentrePortalBuilder termsConditions(String termsConditions) {
        insuranceCentrePortal.setTermsConditions(termsConditions);
        return this;
    }

    public InsuranceCentrePortalBuilder copyright(String copyright) {
        insuranceCentrePortal.setCopyright(copyright);
        return this;
    }

    public InsuranceCentrePortalBuilder headerTitle(String headerTitle) {
        insuranceCentrePortal.setHeaderTitle(headerTitle);
        return this;
    }

    public InsuranceCentrePortalBuilder headerBody(String headerBody) {
        insuranceCentrePortal.setHeaderBody(headerBody);
        return this;
    }

    public InsuranceCentrePortalBuilder footerColor(String footerColor) {
        insuranceCentrePortal.setFooterColor(footerColor);
        return this;
    }

    public InsuranceCentrePortalBuilder backgroundColor(String backgroundColor) {
        insuranceCentrePortal.setBackgroundColor(backgroundColor);
        return this;
    }

    public InsuranceCentrePortalBuilder licensed(boolean licensed) {
        insuranceCentrePortal.setLicensed(licensed);
        return this;
    }

    public InsuranceCentrePortalBuilder defaultLogo(String defaultLogo) {
        insuranceCentrePortal.setDefaultLogo(defaultLogo);
        return this;
    }

    public InsuranceCentrePortalBuilder titleColor(String titleColor) {
        insuranceCentrePortal.setTitleColor(titleColor);
        return this;
    }

    public InsuranceCentrePortalBuilder subTitleColor(String subTitleColor) {
        insuranceCentrePortal.setSubTitleColor(subTitleColor);
        return this;
    }

    public InsuranceCentrePortalBuilder eTrustSymbol(String eTrustSymbol) {
        insuranceCentrePortal.setETrustSymbol(eTrustSymbol);
        return this;
    }

    public InsuranceCentrePortalBuilder digitalMediaOrganizerSymbol(String digitalMediaOrganizerSymbol) {
        insuranceCentrePortal.setDigitalMediaOrganizerSymbol(digitalMediaOrganizerSymbol);
        return this;
    }

    public InsuranceCentrePortalBuilder googlePlus(String googlePlus) {
        insuranceCentrePortal.setGooglePlus(googlePlus);
        return this;
    }

    public InsuranceCentrePortalBuilder telegram(String telegram) {
        insuranceCentrePortal.setTelegram(telegram);
        return this;
    }

    public InsuranceCentrePortalBuilder instagram(String instagram) {
        insuranceCentrePortal.setInstagram(instagram);
        return this;
    }

    public InsuranceCentrePortalBuilder faceBook(String faceBook) {
        insuranceCentrePortal.setFaceBook(faceBook);
        return this;
    }

    public InsuranceCentrePortalBuilder twitter(String twitter) {
        insuranceCentrePortal.setTwitter(twitter);
        return this;
    }

    public InsuranceCentrePortalBuilder saturdayToWednesdayFromHour(String saturdayToWednesdayFromHour) {
        insuranceCentrePortal.setSaturdayToWednesdayFromHour(saturdayToWednesdayFromHour);
        return this;
    }

    public InsuranceCentrePortalBuilder saturdayToWednesdayToHour(String saturdayToWednesdayToHour) {
        insuranceCentrePortal.setSaturdayToWednesdayToHour(saturdayToWednesdayToHour);
        return this;
    }

    public InsuranceCentrePortalBuilder thursdayFromHour(String thursdayFromHour) {
        insuranceCentrePortal.setThursdayFromHour(thursdayFromHour);
        return this;
    }

    public InsuranceCentrePortalBuilder thursdayToHour(String thursdayToHour) {
        insuranceCentrePortal.setThursdayToHour(thursdayToHour);
        return this;
    }

    public InsuranceCentrePortalBuilder fridayFromHour(String fridayFromHour) {
        insuranceCentrePortal.setFridayFromHour(fridayFromHour);
        return this;
    }

    public InsuranceCentrePortalBuilder fridayToHour(String fridayToHour) {
        insuranceCentrePortal.setFridayToHour(fridayToHour);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileHeaderId(int metaMediaFileHeaderId) {
        insuranceCentrePortal.setMetaMediaFileHeaderId(metaMediaFileHeaderId);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileHeaderUrl(String metaMediaFileHeaderUrl) {
        insuranceCentrePortal.setMetaMediaFileHeaderUrl(metaMediaFileHeaderUrl);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileLogoId(int metaMediaFileLogoId) {
        insuranceCentrePortal.setMetaMediaFileLogoId(metaMediaFileLogoId);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileLogoUrl(String metaMediaFileLogoUrl) {
        insuranceCentrePortal.setMetaMediaFileLogoUrl(metaMediaFileLogoUrl);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileFaviconId(int metaMediaFileFaviconId) {
        insuranceCentrePortal.setMetaMediaFileFaviconId(metaMediaFileFaviconId);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileFaviconUrl(String metaMediaFileFaviconUrl) {
        insuranceCentrePortal.setMetaMediaFileFaviconUrl(metaMediaFileFaviconUrl);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileFooterId(String metaMediaFileFooterId) {
        insuranceCentrePortal.setMetaMediaFileFooterId(metaMediaFileFooterId);
        return this;
    }

    public InsuranceCentrePortalBuilder metaMediaFileFooterUrl(String metaMediaFileFooterUrl) {
        insuranceCentrePortal.setMetaMediaFileFooterUrl(metaMediaFileFooterUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsuranceCentrePortal build() {
        return insuranceCentrePortal;
    }
}