/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class InsuranceExtraCoverageExtraData 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4987500457091220005L;
    private boolean defaultStatus;
    private boolean requiringExpertVisit;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("defaultStatus")
    public boolean getDefaultStatus ( ) { 
        return this.defaultStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("defaultStatus")
    public void setDefaultStatus (boolean value) { 
        this.defaultStatus = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("requiringExpertVisit")
    public boolean getRequiringExpertVisit ( ) { 
        return this.requiringExpertVisit;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("requiringExpertVisit")
    public void setRequiringExpertVisit (boolean value) { 
        this.requiringExpertVisit = value;
    }
 
}
