/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsuranceTypesBuilder {
    //the instance to build
    private InsuranceTypes insuranceTypes;

    /**
     * Default constructor to initialize the instance
     */
    public InsuranceTypesBuilder() {
        insuranceTypes = new InsuranceTypes();
    }

    public InsuranceTypesBuilder isSuccess(boolean isSuccess) {
        insuranceTypes.setIsSuccess(isSuccess);
        return this;
    }

    public InsuranceTypesBuilder status(int status) {
        insuranceTypes.setStatus(status);
        return this;
    }

    public InsuranceTypesBuilder message(List<ComboDataModel> message) {
        insuranceTypes.setMessage(message);
        return this;
    }

    public InsuranceTypesBuilder extraData(String extraData) {
        insuranceTypes.setExtraData(extraData);
        return this;
    }

    public InsuranceTypesBuilder exception(String exception) {
        insuranceTypes.setException(exception);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsuranceTypes build() {
        return insuranceTypes;
    }
}