/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class InsuranceGroupBuilder {
    //the instance to build
    private InsuranceGroup insuranceGroup;

    /**
     * Default constructor to initialize the instance
     */
    public InsuranceGroupBuilder() {
        insuranceGroup = new InsuranceGroup();
    }

    public InsuranceGroupBuilder id(int id) {
        insuranceGroup.setId(id);
        return this;
    }

    /**
     * نام گروه بیمه ای
     */
    public InsuranceGroupBuilder title(String title) {
        insuranceGroup.setTitle(title);
        return this;
    }

    public InsuranceGroupBuilder extraData(String extraData) {
        insuranceGroup.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public InsuranceGroup build() {
        return insuranceGroup;
    }
}