/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class LiabilityDoctorInsurancePolicyExtendViewBuilder {
    //the instance to build
    private LiabilityDoctorInsurancePolicyExtendView liabilityDoctorInsurancePolicyExtendView;

    /**
     * Default constructor to initialize the instance
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder() {
        liabilityDoctorInsurancePolicyExtendView = new LiabilityDoctorInsurancePolicyExtendView();
    }

    /**
     * شناسه ی نرخ پوشش پزشکی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder liabilityDoctorCoverageRateId(String liabilityDoctorCoverageRateId) {
        liabilityDoctorInsurancePolicyExtendView.setLiabilityDoctorCoverageRateId(liabilityDoctorCoverageRateId);
        return this;
    }

    /**
     * شناسه ی دوره های فعالیت
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder activityAreaParamId(String activityAreaParamId) {
        liabilityDoctorInsurancePolicyExtendView.setActivityAreaParamId(activityAreaParamId);
        return this;
    }

    /**
     * شاسه ی تخصص
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder expertiseParamId(String expertiseParamId) {
        liabilityDoctorInsurancePolicyExtendView.setExpertiseParamId(expertiseParamId);
        return this;
    }

    /**
     * شناسه ی سقف تعهد
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder commitmentCeilingParamId(String commitmentCeilingParamId) {
        liabilityDoctorInsurancePolicyExtendView.setCommitmentCeilingParamId(commitmentCeilingParamId);
        return this;
    }

    /**
     * شناسه ی تخفیف
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder insuranceRiskLevelId(String insuranceRiskLevelId) {
        liabilityDoctorInsurancePolicyExtendView.setInsuranceRiskLevelId(insuranceRiskLevelId);
        return this;
    }

    /**
     * تاریخ پایان بیمه نامه
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder currentInsuranceDeadline(String currentInsuranceDeadline) {
        liabilityDoctorInsurancePolicyExtendView.setCurrentInsuranceDeadline(currentInsuranceDeadline);
        return this;
    }

    /**
     * نرخ تخفیف پوشش
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder riskLevelDiscountRate(String riskLevelDiscountRate) {
        liabilityDoctorInsurancePolicyExtendView.setRiskLevelDiscountRate(riskLevelDiscountRate);
        return this;
    }

    /**
     * خسارت جانی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder physicalCommitment(String physicalCommitment) {
        liabilityDoctorInsurancePolicyExtendView.setPhysicalCommitment(physicalCommitment);
        return this;
    }

    /**
     * نرخ تخفیف
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder discountRate(String discountRate) {
        liabilityDoctorInsurancePolicyExtendView.setDiscountRate(discountRate);
        return this;
    }

    /**
     * پوشش پایه
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder basePremium(String basePremium) {
        liabilityDoctorInsurancePolicyExtendView.setBasePremium(basePremium);
        return this;
    }

    /**
     * پوشش ها
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder allPremium(String allPremium) {
        liabilityDoctorInsurancePolicyExtendView.setAllPremium(allPremium);
        return this;
    }

    /**
     * اطلاعات اضافه
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder allExtraValues(String allExtraValues) {
        liabilityDoctorInsurancePolicyExtendView.setAllExtraValues(allExtraValues);
        return this;
    }

    /**
     * نرخ تخفیف شرکت بیمه
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder insuranceCompanyDiscountRate(int insuranceCompanyDiscountRate) {
        liabilityDoctorInsurancePolicyExtendView.setInsuranceCompanyDiscountRate(insuranceCompanyDiscountRate);
        return this;
    }

    /**
     * لیست تخفیفات
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder allDiscount(int allDiscount) {
        liabilityDoctorInsurancePolicyExtendView.setAllDiscount(allDiscount);
        return this;
    }

    /**
     * نوع ارز حق بیمه
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder exchangePremium(int exchangePremium) {
        liabilityDoctorInsurancePolicyExtendView.setExchangePremium(exchangePremium);
        return this;
    }

    /**
     * نام پزشک
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder doctorName(String doctorName) {
        liabilityDoctorInsurancePolicyExtendView.setDoctorName(doctorName);
        return this;
    }

    /**
     * شماره ی نظام پزشکی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder medicalSystemNO(String medicalSystemNO) {
        liabilityDoctorInsurancePolicyExtendView.setMedicalSystemNO(medicalSystemNO);
        return this;
    }

    /**
     * آدرس
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder address(String address) {
        liabilityDoctorInsurancePolicyExtendView.setAddress(address);
        return this;
    }

    /**
     * آیا رزیدنت است؟
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder isResident(boolean isResident) {
        liabilityDoctorInsurancePolicyExtendView.setIsResident(isResident);
        return this;
    }

    /**
     * آیا دانشجو است؟
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder isStudent(boolean isStudent) {
        liabilityDoctorInsurancePolicyExtendView.setIsStudent(isStudent);
        return this;
    }

    /**
     * دارای مطب؟
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder hasClinic(String hasClinic) {
        liabilityDoctorInsurancePolicyExtendView.setHasClinic(hasClinic);
        return this;
    }

    /**
     * شناسه ی گواهی نظام پزشکی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder metaMediaMedicalSystemLicenseId(String metaMediaMedicalSystemLicenseId) {
        liabilityDoctorInsurancePolicyExtendView.setMetaMediaMedicalSystemLicenseId(metaMediaMedicalSystemLicenseId);
        return this;
    }

    /**
     * آدرس گواهی نظام پزشکی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder metaMediaMedicalSystemLicenseUrl(String metaMediaMedicalSystemLicenseUrl) {
        liabilityDoctorInsurancePolicyExtendView.setMetaMediaMedicalSystemLicenseUrl(metaMediaMedicalSystemLicenseUrl);
        return this;
    }

    /**
     * شناسه ی کارت ملی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder metaMediaNationalCardId(String metaMediaNationalCardId) {
        liabilityDoctorInsurancePolicyExtendView.setMetaMediaNationalCardId(metaMediaNationalCardId);
        return this;
    }

    /**
     * آدرس کارت ملی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder metaMediaNationalCardUrl(String metaMediaNationalCardUrl) {
        liabilityDoctorInsurancePolicyExtendView.setMetaMediaNationalCardUrl(metaMediaNationalCardUrl);
        return this;
    }

    /**
     * شناسه ی بیمه نامه ی کنونی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder metaMediaCurrentInsurancePolicyId(String metaMediaCurrentInsurancePolicyId) {
        liabilityDoctorInsurancePolicyExtendView.setMetaMediaCurrentInsurancePolicyId(metaMediaCurrentInsurancePolicyId);
        return this;
    }

    /**
     * آدرس بیمه نامه ی کنونی
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder metaMediaCurrentInsurancePolicyUrl(String metaMediaCurrentInsurancePolicyUrl) {
        liabilityDoctorInsurancePolicyExtendView.setMetaMediaCurrentInsurancePolicyUrl(metaMediaCurrentInsurancePolicyUrl);
        return this;
    }

    /**
     * شناسه ی دوره های بیمه نامه
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder activityAreaEnumName(String activityAreaEnumName) {
        liabilityDoctorInsurancePolicyExtendView.setActivityAreaEnumName(activityAreaEnumName);
        return this;
    }

    /**
     * نام دوره ی بیمه نامه
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder activityAreaTitle(String activityAreaTitle) {
        liabilityDoctorInsurancePolicyExtendView.setActivityAreaTitle(activityAreaTitle);
        return this;
    }

    /**
     * نام تخصص
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder expertiseTitle(String expertiseTitle) {
        liabilityDoctorInsurancePolicyExtendView.setExpertiseTitle(expertiseTitle);
        return this;
    }

    /**
     * وضعیت پزشک
     */
    public LiabilityDoctorInsurancePolicyExtendViewBuilder docterStatusTitle(String docterStatusTitle) {
        liabilityDoctorInsurancePolicyExtendView.setDocterStatusTitle(docterStatusTitle);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LiabilityDoctorInsurancePolicyExtendView build() {
        return liabilityDoctorInsurancePolicyExtendView;
    }
}