/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class LiabilityDoctorInsurancePolicyExtendView 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3557727547211888656L;
    private String liabilityDoctorCoverageRateId;
    private String activityAreaParamId;
    private String expertiseParamId;
    private String commitmentCeilingParamId;
    private String insuranceRiskLevelId;
    private String currentInsuranceDeadline;
    private String riskLevelDiscountRate;
    private String physicalCommitment;
    private String discountRate;
    private String basePremium;
    private String allPremium;
    private String allExtraValues;
    private int insuranceCompanyDiscountRate;
    private int allDiscount;
    private int exchangePremium;
    private String doctorName;
    private String medicalSystemNO;
    private String address;
    private boolean isResident;
    private boolean isStudent;
    private String hasClinic;
    private String metaMediaMedicalSystemLicenseId;
    private String metaMediaMedicalSystemLicenseUrl;
    private String metaMediaNationalCardId;
    private String metaMediaNationalCardUrl;
    private String metaMediaCurrentInsurancePolicyId;
    private String metaMediaCurrentInsurancePolicyUrl;
    private String activityAreaEnumName;
    private String activityAreaTitle;
    private String expertiseTitle;
    private String docterStatusTitle;
    /** GETTER
     * شناسه ی نرخ پوشش پزشکی
     */
    @JsonGetter("liabilityDoctorCoverageRateId")
    public String getLiabilityDoctorCoverageRateId ( ) { 
        return this.liabilityDoctorCoverageRateId;
    }
    
    /** SETTER
     * شناسه ی نرخ پوشش پزشکی
     */
    @JsonSetter("liabilityDoctorCoverageRateId")
    public void setLiabilityDoctorCoverageRateId (String value) { 
        this.liabilityDoctorCoverageRateId = value;
    }
 
    /** GETTER
     * شناسه ی دوره های فعالیت
     */
    @JsonGetter("activityAreaParamId")
    public String getActivityAreaParamId ( ) { 
        return this.activityAreaParamId;
    }
    
    /** SETTER
     * شناسه ی دوره های فعالیت
     */
    @JsonSetter("activityAreaParamId")
    public void setActivityAreaParamId (String value) { 
        this.activityAreaParamId = value;
    }
 
    /** GETTER
     * شاسه ی تخصص
     */
    @JsonGetter("expertiseParamId")
    public String getExpertiseParamId ( ) { 
        return this.expertiseParamId;
    }
    
    /** SETTER
     * شاسه ی تخصص
     */
    @JsonSetter("expertiseParamId")
    public void setExpertiseParamId (String value) { 
        this.expertiseParamId = value;
    }
 
    /** GETTER
     * شناسه ی سقف تعهد
     */
    @JsonGetter("commitmentCeilingParamId")
    public String getCommitmentCeilingParamId ( ) { 
        return this.commitmentCeilingParamId;
    }
    
    /** SETTER
     * شناسه ی سقف تعهد
     */
    @JsonSetter("commitmentCeilingParamId")
    public void setCommitmentCeilingParamId (String value) { 
        this.commitmentCeilingParamId = value;
    }
 
    /** GETTER
     * شناسه ی تخفیف
     */
    @JsonGetter("insuranceRiskLevelId")
    public String getInsuranceRiskLevelId ( ) { 
        return this.insuranceRiskLevelId;
    }
    
    /** SETTER
     * شناسه ی تخفیف
     */
    @JsonSetter("insuranceRiskLevelId")
    public void setInsuranceRiskLevelId (String value) { 
        this.insuranceRiskLevelId = value;
    }
 
    /** GETTER
     * تاریخ پایان بیمه نامه
     */
    @JsonGetter("currentInsuranceDeadline")
    public String getCurrentInsuranceDeadline ( ) { 
        return this.currentInsuranceDeadline;
    }
    
    /** SETTER
     * تاریخ پایان بیمه نامه
     */
    @JsonSetter("currentInsuranceDeadline")
    public void setCurrentInsuranceDeadline (String value) { 
        this.currentInsuranceDeadline = value;
    }
 
    /** GETTER
     * نرخ تخفیف پوشش
     */
    @JsonGetter("riskLevelDiscountRate")
    public String getRiskLevelDiscountRate ( ) { 
        return this.riskLevelDiscountRate;
    }
    
    /** SETTER
     * نرخ تخفیف پوشش
     */
    @JsonSetter("riskLevelDiscountRate")
    public void setRiskLevelDiscountRate (String value) { 
        this.riskLevelDiscountRate = value;
    }
 
    /** GETTER
     * خسارت جانی
     */
    @JsonGetter("physicalCommitment")
    public String getPhysicalCommitment ( ) { 
        return this.physicalCommitment;
    }
    
    /** SETTER
     * خسارت جانی
     */
    @JsonSetter("physicalCommitment")
    public void setPhysicalCommitment (String value) { 
        this.physicalCommitment = value;
    }
 
    /** GETTER
     * نرخ تخفیف
     */
    @JsonGetter("discountRate")
    public String getDiscountRate ( ) { 
        return this.discountRate;
    }
    
    /** SETTER
     * نرخ تخفیف
     */
    @JsonSetter("discountRate")
    public void setDiscountRate (String value) { 
        this.discountRate = value;
    }
 
    /** GETTER
     * پوشش پایه
     */
    @JsonGetter("basePremium")
    public String getBasePremium ( ) { 
        return this.basePremium;
    }
    
    /** SETTER
     * پوشش پایه
     */
    @JsonSetter("basePremium")
    public void setBasePremium (String value) { 
        this.basePremium = value;
    }
 
    /** GETTER
     * پوشش ها
     */
    @JsonGetter("allPremium")
    public String getAllPremium ( ) { 
        return this.allPremium;
    }
    
    /** SETTER
     * پوشش ها
     */
    @JsonSetter("allPremium")
    public void setAllPremium (String value) { 
        this.allPremium = value;
    }
 
    /** GETTER
     * اطلاعات اضافه
     */
    @JsonGetter("allExtraValues")
    public String getAllExtraValues ( ) { 
        return this.allExtraValues;
    }
    
    /** SETTER
     * اطلاعات اضافه
     */
    @JsonSetter("allExtraValues")
    public void setAllExtraValues (String value) { 
        this.allExtraValues = value;
    }
 
    /** GETTER
     * نرخ تخفیف شرکت بیمه
     */
    @JsonGetter("insuranceCompanyDiscountRate")
    public int getInsuranceCompanyDiscountRate ( ) { 
        return this.insuranceCompanyDiscountRate;
    }
    
    /** SETTER
     * نرخ تخفیف شرکت بیمه
     */
    @JsonSetter("insuranceCompanyDiscountRate")
    public void setInsuranceCompanyDiscountRate (int value) { 
        this.insuranceCompanyDiscountRate = value;
    }
 
    /** GETTER
     * لیست تخفیفات
     */
    @JsonGetter("allDiscount")
    public int getAllDiscount ( ) { 
        return this.allDiscount;
    }
    
    /** SETTER
     * لیست تخفیفات
     */
    @JsonSetter("allDiscount")
    public void setAllDiscount (int value) { 
        this.allDiscount = value;
    }
 
    /** GETTER
     * نوع ارز حق بیمه
     */
    @JsonGetter("exchangePremium")
    public int getExchangePremium ( ) { 
        return this.exchangePremium;
    }
    
    /** SETTER
     * نوع ارز حق بیمه
     */
    @JsonSetter("exchangePremium")
    public void setExchangePremium (int value) { 
        this.exchangePremium = value;
    }
 
    /** GETTER
     * نام پزشک
     */
    @JsonGetter("doctorName")
    public String getDoctorName ( ) { 
        return this.doctorName;
    }
    
    /** SETTER
     * نام پزشک
     */
    @JsonSetter("doctorName")
    public void setDoctorName (String value) { 
        this.doctorName = value;
    }
 
    /** GETTER
     * شماره ی نظام پزشکی
     */
    @JsonGetter("medicalSystemNO")
    public String getMedicalSystemNO ( ) { 
        return this.medicalSystemNO;
    }
    
    /** SETTER
     * شماره ی نظام پزشکی
     */
    @JsonSetter("medicalSystemNO")
    public void setMedicalSystemNO (String value) { 
        this.medicalSystemNO = value;
    }
 
    /** GETTER
     * آدرس
     */
    @JsonGetter("address")
    public String getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * آدرس
     */
    @JsonSetter("address")
    public void setAddress (String value) { 
        this.address = value;
    }
 
    /** GETTER
     * آیا رزیدنت است؟
     */
    @JsonGetter("isResident")
    public boolean getIsResident ( ) { 
        return this.isResident;
    }
    
    /** SETTER
     * آیا رزیدنت است؟
     */
    @JsonSetter("isResident")
    public void setIsResident (boolean value) { 
        this.isResident = value;
    }
 
    /** GETTER
     * آیا دانشجو است؟
     */
    @JsonGetter("isStudent")
    public boolean getIsStudent ( ) { 
        return this.isStudent;
    }
    
    /** SETTER
     * آیا دانشجو است؟
     */
    @JsonSetter("isStudent")
    public void setIsStudent (boolean value) { 
        this.isStudent = value;
    }
 
    /** GETTER
     * دارای مطب؟
     */
    @JsonGetter("hasClinic")
    public String getHasClinic ( ) { 
        return this.hasClinic;
    }
    
    /** SETTER
     * دارای مطب؟
     */
    @JsonSetter("hasClinic")
    public void setHasClinic (String value) { 
        this.hasClinic = value;
    }
 
    /** GETTER
     * شناسه ی گواهی نظام پزشکی
     */
    @JsonGetter("metaMediaMedicalSystemLicenseId")
    public String getMetaMediaMedicalSystemLicenseId ( ) { 
        return this.metaMediaMedicalSystemLicenseId;
    }
    
    /** SETTER
     * شناسه ی گواهی نظام پزشکی
     */
    @JsonSetter("metaMediaMedicalSystemLicenseId")
    public void setMetaMediaMedicalSystemLicenseId (String value) { 
        this.metaMediaMedicalSystemLicenseId = value;
    }
 
    /** GETTER
     * آدرس گواهی نظام پزشکی
     */
    @JsonGetter("metaMediaMedicalSystemLicenseUrl")
    public String getMetaMediaMedicalSystemLicenseUrl ( ) { 
        return this.metaMediaMedicalSystemLicenseUrl;
    }
    
    /** SETTER
     * آدرس گواهی نظام پزشکی
     */
    @JsonSetter("metaMediaMedicalSystemLicenseUrl")
    public void setMetaMediaMedicalSystemLicenseUrl (String value) { 
        this.metaMediaMedicalSystemLicenseUrl = value;
    }
 
    /** GETTER
     * شناسه ی کارت ملی
     */
    @JsonGetter("metaMediaNationalCardId")
    public String getMetaMediaNationalCardId ( ) { 
        return this.metaMediaNationalCardId;
    }
    
    /** SETTER
     * شناسه ی کارت ملی
     */
    @JsonSetter("metaMediaNationalCardId")
    public void setMetaMediaNationalCardId (String value) { 
        this.metaMediaNationalCardId = value;
    }
 
    /** GETTER
     * آدرس کارت ملی
     */
    @JsonGetter("metaMediaNationalCardUrl")
    public String getMetaMediaNationalCardUrl ( ) { 
        return this.metaMediaNationalCardUrl;
    }
    
    /** SETTER
     * آدرس کارت ملی
     */
    @JsonSetter("metaMediaNationalCardUrl")
    public void setMetaMediaNationalCardUrl (String value) { 
        this.metaMediaNationalCardUrl = value;
    }
 
    /** GETTER
     * شناسه ی بیمه نامه ی کنونی
     */
    @JsonGetter("metaMediaCurrentInsurancePolicyId")
    public String getMetaMediaCurrentInsurancePolicyId ( ) { 
        return this.metaMediaCurrentInsurancePolicyId;
    }
    
    /** SETTER
     * شناسه ی بیمه نامه ی کنونی
     */
    @JsonSetter("metaMediaCurrentInsurancePolicyId")
    public void setMetaMediaCurrentInsurancePolicyId (String value) { 
        this.metaMediaCurrentInsurancePolicyId = value;
    }
 
    /** GETTER
     * آدرس بیمه نامه ی کنونی
     */
    @JsonGetter("metaMediaCurrentInsurancePolicyUrl")
    public String getMetaMediaCurrentInsurancePolicyUrl ( ) { 
        return this.metaMediaCurrentInsurancePolicyUrl;
    }
    
    /** SETTER
     * آدرس بیمه نامه ی کنونی
     */
    @JsonSetter("metaMediaCurrentInsurancePolicyUrl")
    public void setMetaMediaCurrentInsurancePolicyUrl (String value) { 
        this.metaMediaCurrentInsurancePolicyUrl = value;
    }
 
    /** GETTER
     * شناسه ی دوره های بیمه نامه
     */
    @JsonGetter("activityAreaEnumName")
    public String getActivityAreaEnumName ( ) { 
        return this.activityAreaEnumName;
    }
    
    /** SETTER
     * شناسه ی دوره های بیمه نامه
     */
    @JsonSetter("activityAreaEnumName")
    public void setActivityAreaEnumName (String value) { 
        this.activityAreaEnumName = value;
    }
 
    /** GETTER
     * نام دوره ی بیمه نامه
     */
    @JsonGetter("activityAreaTitle")
    public String getActivityAreaTitle ( ) { 
        return this.activityAreaTitle;
    }
    
    /** SETTER
     * نام دوره ی بیمه نامه
     */
    @JsonSetter("activityAreaTitle")
    public void setActivityAreaTitle (String value) { 
        this.activityAreaTitle = value;
    }
 
    /** GETTER
     * نام تخصص
     */
    @JsonGetter("expertiseTitle")
    public String getExpertiseTitle ( ) { 
        return this.expertiseTitle;
    }
    
    /** SETTER
     * نام تخصص
     */
    @JsonSetter("expertiseTitle")
    public void setExpertiseTitle (String value) { 
        this.expertiseTitle = value;
    }
 
    /** GETTER
     * وضعیت پزشک
     */
    @JsonGetter("docterStatusTitle")
    public String getDocterStatusTitle ( ) { 
        return this.docterStatusTitle;
    }
    
    /** SETTER
     * وضعیت پزشک
     */
    @JsonSetter("docterStatusTitle")
    public void setDocterStatusTitle (String value) { 
        this.docterStatusTitle = value;
    }
 
}
