/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class OtherInsuranceTypesBuilder {
    //the instance to build
    private OtherInsuranceTypes otherInsuranceTypes;

    /**
     * Default constructor to initialize the instance
     */
    public OtherInsuranceTypesBuilder() {
        otherInsuranceTypes = new OtherInsuranceTypes();
    }

    public OtherInsuranceTypesBuilder isSuccess(boolean isSuccess) {
        otherInsuranceTypes.setIsSuccess(isSuccess);
        return this;
    }

    public OtherInsuranceTypesBuilder status(int status) {
        otherInsuranceTypes.setStatus(status);
        return this;
    }

    public OtherInsuranceTypesBuilder message(List<ComboDataModel> message) {
        otherInsuranceTypes.setMessage(message);
        return this;
    }

    public OtherInsuranceTypesBuilder extraData(String extraData) {
        otherInsuranceTypes.setExtraData(extraData);
        return this;
    }

    public OtherInsuranceTypesBuilder exception(String exception) {
        otherInsuranceTypes.setException(exception);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public OtherInsuranceTypes build() {
        return otherInsuranceTypes;
    }
}