/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class PortalLandingPage 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5119396139476877374L;
    private boolean licensed;
    private List<InsuranceGroup> insuranceGroup;
    private List<String> insuranceType;
    private List<SummaryCard> summaryCards;
    private List<SummaryNotic> summaryNotics;
    private List<ImageAlbum> imageAlbums;
    private List<VideoGallery> videoGalleries;
    private InsuranceCentre insuranceCentre;
    private InsuranceCentrePortal insuranceCentrePortal;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("licensed")
    public boolean getLicensed ( ) { 
        return this.licensed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("licensed")
    public void setLicensed (boolean value) { 
        this.licensed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceGroup")
    public List<InsuranceGroup> getInsuranceGroup ( ) { 
        return this.insuranceGroup;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceGroup")
    public void setInsuranceGroup (List<InsuranceGroup> value) { 
        this.insuranceGroup = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceType")
    public List<String> getInsuranceType ( ) { 
        return this.insuranceType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceType")
    public void setInsuranceType (List<String> value) { 
        this.insuranceType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("summaryCards")
    public List<SummaryCard> getSummaryCards ( ) { 
        return this.summaryCards;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("summaryCards")
    public void setSummaryCards (List<SummaryCard> value) { 
        this.summaryCards = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("summaryNotics")
    public List<SummaryNotic> getSummaryNotics ( ) { 
        return this.summaryNotics;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("summaryNotics")
    public void setSummaryNotics (List<SummaryNotic> value) { 
        this.summaryNotics = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("imageAlbums")
    public List<ImageAlbum> getImageAlbums ( ) { 
        return this.imageAlbums;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("imageAlbums")
    public void setImageAlbums (List<ImageAlbum> value) { 
        this.imageAlbums = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("videoGalleries")
    public List<VideoGallery> getVideoGalleries ( ) { 
        return this.videoGalleries;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("videoGalleries")
    public void setVideoGalleries (List<VideoGallery> value) { 
        this.videoGalleries = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentre")
    public InsuranceCentre getInsuranceCentre ( ) { 
        return this.insuranceCentre;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentre")
    public void setInsuranceCentre (InsuranceCentre value) { 
        this.insuranceCentre = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentrePortal")
    public InsuranceCentrePortal getInsuranceCentrePortal ( ) { 
        return this.insuranceCentrePortal;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentrePortal")
    public void setInsuranceCentrePortal (InsuranceCentrePortal value) { 
        this.insuranceCentrePortal = value;
    }
 
}
