/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class PortalLandingPageBuilder {
    //the instance to build
    private PortalLandingPage portalLandingPage;

    /**
     * Default constructor to initialize the instance
     */
    public PortalLandingPageBuilder() {
        portalLandingPage = new PortalLandingPage();
    }

    public PortalLandingPageBuilder licensed(boolean licensed) {
        portalLandingPage.setLicensed(licensed);
        return this;
    }

    public PortalLandingPageBuilder insuranceGroup(List<InsuranceGroup> insuranceGroup) {
        portalLandingPage.setInsuranceGroup(insuranceGroup);
        return this;
    }

    public PortalLandingPageBuilder insuranceType(List<String> insuranceType) {
        portalLandingPage.setInsuranceType(insuranceType);
        return this;
    }

    public PortalLandingPageBuilder summaryCards(List<SummaryCard> summaryCards) {
        portalLandingPage.setSummaryCards(summaryCards);
        return this;
    }

    public PortalLandingPageBuilder summaryNotics(List<SummaryNotic> summaryNotics) {
        portalLandingPage.setSummaryNotics(summaryNotics);
        return this;
    }

    public PortalLandingPageBuilder imageAlbums(List<ImageAlbum> imageAlbums) {
        portalLandingPage.setImageAlbums(imageAlbums);
        return this;
    }

    public PortalLandingPageBuilder videoGalleries(List<VideoGallery> videoGalleries) {
        portalLandingPage.setVideoGalleries(videoGalleries);
        return this;
    }

    public PortalLandingPageBuilder insuranceCentre(InsuranceCentre insuranceCentre) {
        portalLandingPage.setInsuranceCentre(insuranceCentre);
        return this;
    }

    public PortalLandingPageBuilder insuranceCentrePortal(InsuranceCentrePortal insuranceCentrePortal) {
        portalLandingPage.setInsuranceCentrePortal(insuranceCentrePortal);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PortalLandingPage build() {
        return portalLandingPage;
    }
}