/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class SpecialPlanBuilder {
    //the instance to build
    private SpecialPlan specialPlan;

    /**
     * Default constructor to initialize the instance
     */
    public SpecialPlanBuilder() {
        specialPlan = new SpecialPlan();
    }

    public SpecialPlanBuilder key(int key) {
        specialPlan.setKey(key);
        return this;
    }

    public SpecialPlanBuilder count(int count) {
        specialPlan.setCount(count);
        return this;
    }

    public SpecialPlanBuilder title(String title) {
        specialPlan.setTitle(title);
        return this;
    }

    public SpecialPlanBuilder policyType(int policyType) {
        specialPlan.setPolicyType(policyType);
        return this;
    }

    public SpecialPlanBuilder display(String display) {
        specialPlan.setDisplay(display);
        return this;
    }

    public SpecialPlanBuilder iconPosition(int iconPosition) {
        specialPlan.setIconPosition(iconPosition);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SpecialPlan build() {
        return specialPlan;
    }
}