/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class StatusStatusCollectionsBuilder {
    //the instance to build
    private StatusStatusCollections statusStatusCollections;

    /**
     * Default constructor to initialize the instance
     */
    public StatusStatusCollectionsBuilder() {
        statusStatusCollections = new StatusStatusCollections();
    }

    public StatusStatusCollectionsBuilder id(String id) {
        statusStatusCollections.setId(id);
        return this;
    }

    public StatusStatusCollectionsBuilder parentId(String parentId) {
        statusStatusCollections.setParentId(parentId);
        return this;
    }

    public StatusStatusCollectionsBuilder statusType(int statusType) {
        statusStatusCollections.setStatusType(statusType);
        return this;
    }

    public StatusStatusCollectionsBuilder title(String title) {
        statusStatusCollections.setTitle(title);
        return this;
    }

    public StatusStatusCollectionsBuilder iconName(String iconName) {
        statusStatusCollections.setIconName(iconName);
        return this;
    }

    public StatusStatusCollectionsBuilder description(String description) {
        statusStatusCollections.setDescription(description);
        return this;
    }

    public StatusStatusCollectionsBuilder editable(boolean editable) {
        statusStatusCollections.setEditable(editable);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public StatusStatusCollections build() {
        return statusStatusCollections;
    }
}