/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class StatusStatusCollections 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5770363342833127875L;
    private String id;
    private String parentId;
    private int statusType;
    private String title;
    private String iconName;
    private String description;
    private boolean editable;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("parentId")
    public String getParentId ( ) { 
        return this.parentId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("parentId")
    public void setParentId (String value) { 
        this.parentId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("statusType")
    public int getStatusType ( ) { 
        return this.statusType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("statusType")
    public void setStatusType (int value) { 
        this.statusType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("iconName")
    public String getIconName ( ) { 
        return this.iconName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("iconName")
    public void setIconName (String value) { 
        this.iconName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("editable")
    public boolean getEditable ( ) { 
        return this.editable;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("editable")
    public void setEditable (boolean value) { 
        this.editable = value;
    }
 
}
