/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class StatusBuilder {
    //the instance to build
    private Status status;

    /**
     * Default constructor to initialize the instance
     */
    public StatusBuilder() {
        status = new Status();
    }

    public StatusBuilder id(String id) {
        status.setId(id);
        return this;
    }

    public StatusBuilder entityId(String entityId) {
        status.setEntityId(entityId);
        return this;
    }

    public StatusBuilder primaryEntityName(int primaryEntityName) {
        status.setPrimaryEntityName(primaryEntityName);
        return this;
    }

    public StatusBuilder statusCollectionId(String statusCollectionId) {
        status.setStatusCollectionId(statusCollectionId);
        return this;
    }

    public StatusBuilder formData(String formData) {
        status.setFormData(formData);
        return this;
    }

    public StatusBuilder statusTitle(String statusTitle) {
        status.setStatusTitle(statusTitle);
        return this;
    }

    public StatusBuilder editable(boolean editable) {
        status.setEditable(editable);
        return this;
    }

    public StatusBuilder statusCollectionParentId(String statusCollectionParentId) {
        status.setStatusCollectionParentId(statusCollectionParentId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Status build() {
        return status;
    }
}