/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class SummaryCardBuilder {
    //the instance to build
    private SummaryCard summaryCard;

    /**
     * Default constructor to initialize the instance
     */
    public SummaryCardBuilder() {
        summaryCard = new SummaryCard();
    }

    public SummaryCardBuilder id(int id) {
        summaryCard.setId(id);
        return this;
    }

    public SummaryCardBuilder insuranceCentreId(int insuranceCentreId) {
        summaryCard.setInsuranceCentreId(insuranceCentreId);
        return this;
    }

    public SummaryCardBuilder articleType(int articleType) {
        summaryCard.setArticleType(articleType);
        return this;
    }

    public SummaryCardBuilder title(String title) {
        summaryCard.setTitle(title);
        return this;
    }

    public SummaryCardBuilder summary(String summary) {
        summaryCard.setSummary(summary);
        return this;
    }

    public SummaryCardBuilder articleGroup(String articleGroup) {
        summaryCard.setArticleGroup(articleGroup);
        return this;
    }

    public SummaryCardBuilder metaMediaFileId(int metaMediaFileId) {
        summaryCard.setMetaMediaFileId(metaMediaFileId);
        return this;
    }

    public SummaryCardBuilder metaMediaFileUrl(String metaMediaFileUrl) {
        summaryCard.setMetaMediaFileUrl(metaMediaFileUrl);
        return this;
    }

    public SummaryCardBuilder publishPersianDate(String publishPersianDate) {
        summaryCard.setPublishPersianDate(publishPersianDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SummaryCard build() {
        return summaryCard;
    }
}