/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class TargetSiteBuilder {
    //the instance to build
    private TargetSite targetSite;

    /**
     * Default constructor to initialize the instance
     */
    public TargetSiteBuilder() {
        targetSite = new TargetSite();
    }

    public TargetSiteBuilder name(String name) {
        targetSite.setName(name);
        return this;
    }

    public TargetSiteBuilder assemblyName(String assemblyName) {
        targetSite.setAssemblyName(assemblyName);
        return this;
    }

    public TargetSiteBuilder className(String className) {
        targetSite.setClassName(className);
        return this;
    }

    public TargetSiteBuilder signature(String signature) {
        targetSite.setSignature(signature);
        return this;
    }

    public TargetSiteBuilder signature2(String signature2) {
        targetSite.setSignature2(signature2);
        return this;
    }

    public TargetSiteBuilder memberType(int memberType) {
        targetSite.setMemberType(memberType);
        return this;
    }

    public TargetSiteBuilder genericArguments(String genericArguments) {
        targetSite.setGenericArguments(genericArguments);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TargetSite build() {
        return targetSite;
    }
}