/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class TrackingDamageFileTrackinCodeBuilder {
    //the instance to build
    private TrackingDamageFileTrackinCode trackingDamageFileTrackinCode;

    /**
     * Default constructor to initialize the instance
     */
    public TrackingDamageFileTrackinCodeBuilder() {
        trackingDamageFileTrackinCode = new TrackingDamageFileTrackinCode();
    }

    public TrackingDamageFileTrackinCodeBuilder id(int id) {
        trackingDamageFileTrackinCode.setId(id);
        return this;
    }

    public TrackingDamageFileTrackinCodeBuilder trackingDamageStatusId(int trackingDamageStatusId) {
        trackingDamageFileTrackinCode.setTrackingDamageStatusId(trackingDamageStatusId);
        return this;
    }

    public TrackingDamageFileTrackinCodeBuilder fileName(String fileName) {
        trackingDamageFileTrackinCode.setFileName(fileName);
        return this;
    }

    public TrackingDamageFileTrackinCodeBuilder title(String title) {
        trackingDamageFileTrackinCode.setTitle(title);
        return this;
    }

    public TrackingDamageFileTrackinCodeBuilder url(String url) {
        trackingDamageFileTrackinCode.setUrl(url);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TrackingDamageFileTrackinCode build() {
        return trackingDamageFileTrackinCode;
    }
}