/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TrackingDamageRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 1596158716922806179L;
    private int personalityType;
    private List<TrackingDamageStatus> trackingDamageStatus;
    private String description;
    private int insuranceTypeId;
    private int insuranceCompanyId;
    private String insurancePolicyNumber;
    private String damageType;
    private String name;
    private String nationalCode;
    private String mobile;
    private String insuredProfile;
    private String subDomain;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("personalityType")
    public int getPersonalityType ( ) { 
        return this.personalityType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("personalityType")
    public void setPersonalityType (int value) { 
        this.personalityType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("trackingDamageStatus")
    public List<TrackingDamageStatus> getTrackingDamageStatus ( ) { 
        return this.trackingDamageStatus;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("trackingDamageStatus")
    public void setTrackingDamageStatus (List<TrackingDamageStatus> value) { 
        this.trackingDamageStatus = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceTypeId")
    public int getInsuranceTypeId ( ) { 
        return this.insuranceTypeId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceTypeId")
    public void setInsuranceTypeId (int value) { 
        this.insuranceTypeId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyId")
    public int getInsuranceCompanyId ( ) { 
        return this.insuranceCompanyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyId")
    public void setInsuranceCompanyId (int value) { 
        this.insuranceCompanyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insurancePolicyNumber")
    public String getInsurancePolicyNumber ( ) { 
        return this.insurancePolicyNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insurancePolicyNumber")
    public void setInsurancePolicyNumber (String value) { 
        this.insurancePolicyNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("damageType")
    public String getDamageType ( ) { 
        return this.damageType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("damageType")
    public void setDamageType (String value) { 
        this.damageType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("nationalCode")
    public String getNationalCode ( ) { 
        return this.nationalCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("nationalCode")
    public void setNationalCode (String value) { 
        this.nationalCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mobile")
    public String getMobile ( ) { 
        return this.mobile;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mobile")
    public void setMobile (String value) { 
        this.mobile = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuredProfile")
    public String getInsuredProfile ( ) { 
        return this.insuredProfile;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuredProfile")
    public void setInsuredProfile (String value) { 
        this.insuredProfile = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("subDomain")
    public String getSubDomain ( ) { 
        return this.subDomain;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("subDomain")
    public void setSubDomain (String value) { 
        this.subDomain = value;
    }
 
}
