/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class TravelDurationBuilder {
    //the instance to build
    private TravelDuration travelDuration;

    /**
     * Default constructor to initialize the instance
     */
    public TravelDurationBuilder() {
        travelDuration = new TravelDuration();
    }

    public TravelDurationBuilder id(int id) {
        travelDuration.setId(id);
        return this;
    }

    public TravelDurationBuilder title(String title) {
        travelDuration.setTitle(title);
        return this;
    }

    public TravelDurationBuilder extraData(String extraData) {
        travelDuration.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TravelDuration build() {
        return travelDuration;
    }
}