/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class TravelInsuranceBuilder {
    //the instance to build
    private TravelInsurance travelInsurance;

    /**
     * Default constructor to initialize the instance
     */
    public TravelInsuranceBuilder() {
        travelInsurance = new TravelInsurance();
    }

    public TravelInsuranceBuilder hasPlan(boolean hasPlan) {
        travelInsurance.setHasPlan(hasPlan);
        return this;
    }

    public TravelInsuranceBuilder isSamanInsurance(boolean isSamanInsurance) {
        travelInsurance.setIsSamanInsurance(isSamanInsurance);
        return this;
    }

    public TravelInsuranceBuilder zones(List<Zone> zones) {
        travelInsurance.setZones(zones);
        return this;
    }

    public TravelInsuranceBuilder travelDurations(List<TravelDuration> travelDurations) {
        travelInsurance.setTravelDurations(travelDurations);
        return this;
    }

    public TravelInsuranceBuilder travelAges(List<TravelAge> travelAges) {
        travelInsurance.setTravelAges(travelAges);
        return this;
    }

    public TravelInsuranceBuilder provinces(List<Province> provinces) {
        travelInsurance.setProvinces(provinces);
        return this;
    }

    public TravelInsuranceBuilder cities(List<String> cities) {
        travelInsurance.setCities(cities);
        return this;
    }

    public TravelInsuranceBuilder cityRegions(List<String> cityRegions) {
        travelInsurance.setCityRegions(cityRegions);
        return this;
    }

    public TravelInsuranceBuilder shippingTypes(List<ShippingType> shippingTypes) {
        travelInsurance.setShippingTypes(shippingTypes);
        return this;
    }

    public TravelInsuranceBuilder postTypes(List<PostType> postTypes) {
        travelInsurance.setPostTypes(postTypes);
        return this;
    }

    public TravelInsuranceBuilder insuranceData(InsuranceDataTravelInsurance insuranceData) {
        travelInsurance.setInsuranceData(insuranceData);
        return this;
    }

    public TravelInsuranceBuilder insurancePolicyCondition(InsurancePolicyCondition insurancePolicyCondition) {
        travelInsurance.setInsurancePolicyCondition(insurancePolicyCondition);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TravelInsurance build() {
        return travelInsurance;
    }
}