/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class TravelAgeBuilder {
    //the instance to build
    private TravelAge travelAge;

    /**
     * Default constructor to initialize the instance
     */
    public TravelAgeBuilder() {
        travelAge = new TravelAge();
    }

    public TravelAgeBuilder id(int id) {
        travelAge.setId(id);
        return this;
    }

    public TravelAgeBuilder title(String title) {
        travelAge.setTitle(title);
        return this;
    }

    public TravelAgeBuilder extraData(String extraData) {
        travelAge.setExtraData(extraData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TravelAge build() {
        return travelAge;
    }
}