/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TravelInsurancePolicyExtendView 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3103210335323270612L;
    private TravelInsurancePolicyExtend travelInsurancePolicyExtend;
    private List<String> travelInsurancePolicyExtendAges;
    private List<String> travelInsurancePolicyExtendPassengers;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("travelInsurancePolicyExtend")
    public TravelInsurancePolicyExtend getTravelInsurancePolicyExtend ( ) { 
        return this.travelInsurancePolicyExtend;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("travelInsurancePolicyExtend")
    public void setTravelInsurancePolicyExtend (TravelInsurancePolicyExtend value) { 
        this.travelInsurancePolicyExtend = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("travelInsurancePolicyExtendAges")
    public List<String> getTravelInsurancePolicyExtendAges ( ) { 
        return this.travelInsurancePolicyExtendAges;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("travelInsurancePolicyExtendAges")
    public void setTravelInsurancePolicyExtendAges (List<String> value) { 
        this.travelInsurancePolicyExtendAges = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("travelInsurancePolicyExtendPassengers")
    public List<String> getTravelInsurancePolicyExtendPassengers ( ) { 
        return this.travelInsurancePolicyExtendPassengers;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("travelInsurancePolicyExtendPassengers")
    public void setTravelInsurancePolicyExtendPassengers (List<String> value) { 
        this.travelInsurancePolicyExtendPassengers = value;
    }
 
}
