/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;

public class TravelInsurancePolicyExtendViewBuilder {
    //the instance to build
    private TravelInsurancePolicyExtendView travelInsurancePolicyExtendView;

    /**
     * Default constructor to initialize the instance
     */
    public TravelInsurancePolicyExtendViewBuilder() {
        travelInsurancePolicyExtendView = new TravelInsurancePolicyExtendView();
    }

    public TravelInsurancePolicyExtendViewBuilder travelInsurancePolicyExtend(TravelInsurancePolicyExtend travelInsurancePolicyExtend) {
        travelInsurancePolicyExtendView.setTravelInsurancePolicyExtend(travelInsurancePolicyExtend);
        return this;
    }

    public TravelInsurancePolicyExtendViewBuilder travelInsurancePolicyExtendAges(List<String> travelInsurancePolicyExtendAges) {
        travelInsurancePolicyExtendView.setTravelInsurancePolicyExtendAges(travelInsurancePolicyExtendAges);
        return this;
    }

    public TravelInsurancePolicyExtendViewBuilder travelInsurancePolicyExtendPassengers(List<String> travelInsurancePolicyExtendPassengers) {
        travelInsurancePolicyExtendView.setTravelInsurancePolicyExtendPassengers(travelInsurancePolicyExtendPassengers);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TravelInsurancePolicyExtendView build() {
        return travelInsurancePolicyExtendView;
    }
}