/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TravelInsurancePolicyFilter 
        implements java.io.Serializable {
    private static final long serialVersionUID = 8492633055122564089L;
    private String zoneIds;
    private String travelRatePlanId;
    private String travelInsurancePolicyExtendAges;
    private String travelDurationParam;
    private String birthDatePersian;
    private String insuranceExtraCoverageIds;
    private String policyTermId;
    private String insuranceCentreSubDomainName;
    private String insuranceCentreId;
    private String insuranceCompanyId;
    private boolean isSearchQuery;
    private String giftCode;
    private String customerUserId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("zoneIds")
    public String getZoneIds ( ) { 
        return this.zoneIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("zoneIds")
    public void setZoneIds (String value) { 
        this.zoneIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("travelRatePlanId")
    public String getTravelRatePlanId ( ) { 
        return this.travelRatePlanId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("travelRatePlanId")
    public void setTravelRatePlanId (String value) { 
        this.travelRatePlanId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("travelInsurancePolicyExtendAges")
    public String getTravelInsurancePolicyExtendAges ( ) { 
        return this.travelInsurancePolicyExtendAges;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("travelInsurancePolicyExtendAges")
    public void setTravelInsurancePolicyExtendAges (String value) { 
        this.travelInsurancePolicyExtendAges = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("travelDurationParam")
    public String getTravelDurationParam ( ) { 
        return this.travelDurationParam;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("travelDurationParam")
    public void setTravelDurationParam (String value) { 
        this.travelDurationParam = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("birthDatePersian")
    public String getBirthDatePersian ( ) { 
        return this.birthDatePersian;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("birthDatePersian")
    public void setBirthDatePersian (String value) { 
        this.birthDatePersian = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceExtraCoverageIds")
    public String getInsuranceExtraCoverageIds ( ) { 
        return this.insuranceExtraCoverageIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceExtraCoverageIds")
    public void setInsuranceExtraCoverageIds (String value) { 
        this.insuranceExtraCoverageIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("policyTermId")
    public String getPolicyTermId ( ) { 
        return this.policyTermId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("policyTermId")
    public void setPolicyTermId (String value) { 
        this.policyTermId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreSubDomainName")
    public String getInsuranceCentreSubDomainName ( ) { 
        return this.insuranceCentreSubDomainName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreSubDomainName")
    public void setInsuranceCentreSubDomainName (String value) { 
        this.insuranceCentreSubDomainName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCentreId")
    public String getInsuranceCentreId ( ) { 
        return this.insuranceCentreId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCentreId")
    public void setInsuranceCentreId (String value) { 
        this.insuranceCentreId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("insuranceCompanyId")
    public String getInsuranceCompanyId ( ) { 
        return this.insuranceCompanyId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("insuranceCompanyId")
    public void setInsuranceCompanyId (String value) { 
        this.insuranceCompanyId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("isSearchQuery")
    public boolean getIsSearchQuery ( ) { 
        return this.isSearchQuery;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("isSearchQuery")
    public void setIsSearchQuery (boolean value) { 
        this.isSearchQuery = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("giftCode")
    public String getGiftCode ( ) { 
        return this.giftCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("giftCode")
    public void setGiftCode (String value) { 
        this.giftCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customerUserId")
    public String getCustomerUserId ( ) { 
        return this.customerUserId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customerUserId")
    public void setCustomerUserId (String value) { 
        this.customerUserId = value;
    }
 
}
