/*
 * EasyBimehLandingLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package ir.notifaano.server.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import ir.notifaano.server.*;
import ir.notifaano.server.models.*;
import ir.notifaano.server.exceptions.*;
import ir.notifaano.server.http.client.HttpClient;
import ir.notifaano.server.http.client.HttpContext;
import ir.notifaano.server.http.request.HttpRequest;
import ir.notifaano.server.http.response.HttpResponse;
import ir.notifaano.server.http.response.HttpStringResponse;
import ir.notifaano.server.http.client.APICallBack;
import ir.notifaano.server.controllers.syncwrapper.APICallBackCatcher;

public class ComboDataController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static ComboDataController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the ComboDataController class 
     */
    public static ComboDataController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new ComboDataController();
                }
            }
        }
        return instance;
    }

    /**
     * دریافت لیست نوع خسارت
     * @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
     * @return    Returns the BaseModelDamageType response from the API call 
     */
    public BaseModelDamageType getDamageType(
                final String xApiKey
    ) throws Throwable {

        HttpRequest _request = _buildGetDamageTypeRequest(xApiKey);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetDamageTypeResponse(_context);
    }

    /**
     * دریافت لیست نوع خسارت
     * @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
     */
    public void getDamageTypeAsync(
                final String xApiKey,
                final APICallBack<BaseModelDamageType> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetDamageTypeRequest(xApiKey);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            BaseModelDamageType returnValue = _handleGetDamageTypeResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getDamageType
     */
    private HttpRequest _buildGetDamageTypeRequest(
                final String xApiKey) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.getBaseUri();

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/DamageType");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("x-api-key", xApiKey);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getDamageType
     * @return An object of type BaseModelDamageType
     */
    private BaseModelDamageType _handleGetDamageTypeResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        BaseModelDamageType _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<BaseModelDamageType>(){});

        return _result;
    }

    /**
     * دریافت لیست نوع بیمه نامه
     * @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
     * @param    issueInsurance    Required parameter: دریافت بیمه نامه های قابل صدور
     * @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
     * @return    Returns the InsuranceTypes response from the API call 
     */
    public InsuranceTypes getInsuranceTypes(
                final String subDomain,
                final boolean issueInsurance,
                final String xApiKey
    ) throws Throwable {

        HttpRequest _request = _buildGetInsuranceTypesRequest(subDomain, issueInsurance, xApiKey);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetInsuranceTypesResponse(_context);
    }

    /**
     * دریافت لیست نوع بیمه نامه
     * @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
     * @param    issueInsurance    Required parameter: دریافت بیمه نامه های قابل صدور
     * @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
     */
    public void getInsuranceTypesAsync(
                final String subDomain,
                final boolean issueInsurance,
                final String xApiKey,
                final APICallBack<InsuranceTypes> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetInsuranceTypesRequest(subDomain, issueInsurance, xApiKey);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            InsuranceTypes returnValue = _handleGetInsuranceTypesResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getInsuranceTypes
     */
    private HttpRequest _buildGetInsuranceTypesRequest(
                final String subDomain,
                final boolean issueInsurance,
                final String xApiKey) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.getBaseUri();

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/ComboData/InsuranceTypes");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("subDomain", subDomain);
        _queryParameters.put("issueInsurance", issueInsurance);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("x-api-key", xApiKey);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getInsuranceTypes
     * @return An object of type InsuranceTypes
     */
    private InsuranceTypes _handleGetInsuranceTypesResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        InsuranceTypes _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<InsuranceTypes>(){});

        return _result;
    }

    /**
     * دریافت لیست شرکت های بیمه
     * @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
     * @param    insuranceTypeId    Required parameter: شناسه ی نوع بیمه نامه
     * @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
     * @return    Returns the InsuranceCompanies response from the API call 
     */
    public InsuranceCompanies getInsuranceCompanies(
                final String subDomain,
                final int insuranceTypeId,
                final String xApiKey
    ) throws Throwable {

        HttpRequest _request = _buildGetInsuranceCompaniesRequest(subDomain, insuranceTypeId, xApiKey);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetInsuranceCompaniesResponse(_context);
    }

    /**
     * دریافت لیست شرکت های بیمه
     * @param    subDomain    Required parameter: دامنه یا زیر دامنه ی مرکز بیمه
     * @param    insuranceTypeId    Required parameter: شناسه ی نوع بیمه نامه
     * @param    xApiKey    Required parameter: کلید اختصاصی ارتباط با سرور
     */
    public void getInsuranceCompaniesAsync(
                final String subDomain,
                final int insuranceTypeId,
                final String xApiKey,
                final APICallBack<InsuranceCompanies> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetInsuranceCompaniesRequest(subDomain, insuranceTypeId, xApiKey);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            InsuranceCompanies returnValue = _handleGetInsuranceCompaniesResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getInsuranceCompanies
     */
    private HttpRequest _buildGetInsuranceCompaniesRequest(
                final String subDomain,
                final int insuranceTypeId,
                final String xApiKey) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.getBaseUri();

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/ComboData/InsuranceCompanies");

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("subDomain", subDomain);
        _queryParameters.put("insuranceTypeId", insuranceTypeId);
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("x-api-key", xApiKey);
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getInsuranceCompanies
     * @return An object of type InsuranceCompanies
     */
    private InsuranceCompanies _handleGetInsuranceCompaniesResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        InsuranceCompanies _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<InsuranceCompanies>(){});

        return _result;
    }

}
